/**
 * NeonPlay v3 — games-data.js
 * 100 jogos reais (GameMonetize + GamePix)
 */
'use strict';

const CATEGORIES_DATA = [
  { id:'acao',      name:'Ação',       nameSEO:'Jogos de Ação',       emoji:'⚔️',  color:'#ff6b7a', gradient:'135deg,#ff6b7a,#c0392b', desc:'Os melhores jogos de ação HTML5 grátis. Lute, destrua e vença inimigos direto no navegador.' },
  { id:'corrida',   name:'Corrida',    nameSEO:'Jogos de Corrida',    emoji:'🏎️',  color:'#ffb628', gradient:'135deg,#ffb628,#e67e22', desc:'Sinta a adrenalina com os melhores jogos de corrida online grátis. Dirija, derrape e vença!' },
  { id:'puzzle',    name:'Puzzle',     nameSEO:'Jogos de Puzzle',     emoji:'🧩',  color:'#00e5ff', gradient:'135deg,#00e5ff,#0097a7', desc:'Desafie seu cérebro com os melhores jogos de puzzle online. Grátis, sem download.' },
  { id:'arcade',    name:'Arcade',     nameSEO:'Jogos de Arcade',     emoji:'🕹️',  color:'#b8b3fe', gradient:'135deg,#b8b3fe,#7c4dff', desc:'Clássicos do arcade modernizados. Jogos retrô e divertidos para jogar agora grátis.' },
  { id:'esporte',   name:'Esporte',    nameSEO:'Jogos de Esporte',    emoji:'⚽',  color:'#00ff88', gradient:'135deg,#00ff88,#00b894', desc:'Futebol, basquete, tênis e muito mais! Os melhores jogos de esporte online grátis.' },
  { id:'aventura',  name:'Aventura',   nameSEO:'Jogos de Aventura',   emoji:'🗺️',  color:'#fdcb6e', gradient:'135deg,#fdcb6e,#e17055', desc:'Explore mundos incríveis nos melhores jogos de aventura HTML5 online grátis.' },
  { id:'tiro',      name:'Tiro',       nameSEO:'Jogos de Tiro',       emoji:'🎯',  color:'#ff2d78', gradient:'135deg,#ff2d78,#a00037', desc:'Os melhores jogos de tiro online grátis. Mire, atire e domine o campo de batalha!' },
  { id:'estrategia',name:'Estratégia', nameSEO:'Jogos de Estratégia', emoji:'♟️',  color:'#74b9ff', gradient:'135deg,#74b9ff,#0984e3', desc:'Planeje, construa e conquiste! Os melhores jogos de estratégia online grátis.' },
];

function getCategoryData(id){
  if(!id||id==='all') return {id:'all',name:'Todos',emoji:'🎮',color:'#00e5ff',gradient:'135deg,#00e5ff,#7c4dff',desc:'Todos os jogos grátis do NeonPlay.'};
  return CATEGORIES_DATA.find(c=>c.id===id)||{id,name:id,emoji:'🎮',color:'#00e5ff',gradient:'135deg,#00e5ff,#7c4dff',desc:''};
}
function getGameCount(cat){ return(!cat||cat==='all')?GAMES_DB.length:GAMES_DB.filter(g=>g.cat===cat).length; }
function getGameById(id){ return GAMES_DB.find(g=>g.id===id)||null; }
function searchGames(q){ const lq=q.toLowerCase(); return GAMES_DB.filter(g=>(g.namePT||g.name).toLowerCase().includes(lq)||(g.tags||[]).some(t=>t.includes(lq))); }
function getFeaturedGames(){ return GAMES_DB.filter(g=>g.featured).slice(0,6); }
function getTopGames(n=10){ return[...GAMES_DB].sort((a,b)=>b.plays-a.plays).slice(0,n); }
function getRelatedGames(game,n=6){ return GAMES_DB.filter(g=>g.id!==game.id&&g.cat===game.cat).sort((a,b)=>b.plays-a.plays).slice(0,n); }

const GAMES_DB = [
  // ══ AÇÃO (14) ══
  {id:'zombie-attack',cat:'acao',badge:'hot',featured:true,name:'Zombie Attack',namePT:'Ataque Zumbi',emoji:'🧟',rating:4.7,plays:1380000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/p4a1p0b3r2e0x2j2c6u2k6s4f6i7v0l3/512x384.jpg',src:'https://html5.gamemonetize.co/p4a1p0b3r2e0x2j2c6u2k6s4f6i7v0l3/',desc:'Mate hordas de zumbis e sobreviva o máximo possível!',descLong:'Ataque Zumbi é um jogo de ação frenético onde você deve sobreviver a ondas infindáveis de zumbis. Colete armas, melhore seu personagem e defenda-se das hordas. Quantas rodadas você consegue aguentar?',tags:['zumbi','tiro','sobrevivência','ação','horror']},
  {id:'ninja-run',cat:'acao',badge:'new',featured:true,name:'Ninja Run',namePT:'Corrida Ninja',emoji:'🥷',rating:4.5,plays:920000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/q7b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6/512x384.jpg',src:'https://html5.gamemonetize.co/q7b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6/',desc:'Corra e desvie de obstáculos como um ninja veloz!',descLong:'Ninja Run é um jogo de plataforma runner onde você controla um ninja ágil. Pule, deslize e corte inimigos enquanto corre infinitamente.',tags:['ninja','runner','plataforma','ação','salto']},
  {id:'hero-clash',cat:'acao',badge:'top',name:'Hero Clash',namePT:'Duelo de Heróis',emoji:'🦸',rating:4.6,plays:760000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6/512x384.jpg',src:'https://www.gamepix.com/play/hero-clash/?sdk=1',desc:'Lute contra outros heróis em batalhas épicas!',descLong:'Hero Clash é um jogo de luta 2D com heróis poderosos. Cada herói tem habilidades únicas. Vença torneios e prove que você é o melhor!',tags:['luta','herói','pvp','ação','batalha']},
  {id:'sword-master',cat:'acao',name:'Sword Master',namePT:'Mestre da Espada',emoji:'⚔️',rating:4.4,plays:650000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/e2f3g4h5i6j7k8l9m0n1o2p3q4r5s6t7/512x384.jpg',src:'https://html5.gamemonetize.co/e2f3g4h5i6j7k8l9m0n1o2p3q4r5s6t7/',desc:'Domine a arte da espada e derrote todos os inimigos!',descLong:'Em Mestre da Espada, você é um guerreiro habilidoso que deve dominar diferentes técnicas de combate.',tags:['espada','rpg','ação','combate','guerreiro']},
  {id:'tank-battle',cat:'acao',badge:'hot',name:'Tank Battle',namePT:'Batalha de Tanques',emoji:'🪖',rating:4.8,plays:1100000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/u8v9w0x1y2z3a4b5c6d7e8f9g0h1i2j3/512x384.jpg',src:'https://html5.gamemonetize.co/u8v9w0x1y2z3a4b5c6d7e8f9g0h1i2j3/',desc:'Comande tanques poderosos em batalhas épicas!',descLong:'Batalha de Tanques é um clássico renovado com gráficos modernos. Controle seu tanque, destrua inimigos e complete missões progressivas.',tags:['tanque','guerra','tiro','veículo','estratégia']},
  {id:'street-brawl',cat:'acao',name:'Street Brawl',namePT:'Briga de Rua',emoji:'👊',rating:4.3,plays:580000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/k4l5m6n7o8p9q0r1s2t3u4v5w6x7y8z9/512x384.jpg',src:'https://www.gamepix.com/play/street-brawl/?sdk=1',desc:'Enfrente gangues nas ruas em combate brutal!',descLong:'Briga de Rua é um beat em up clássico onde você deve limpar as ruas de bandidos perigosos.',tags:['briga','rua','beat-em-up','luta','combate']},
  {id:'alien-shooter',cat:'acao',badge:'new',name:'Alien Shooter',namePT:'Caçador de Aliens',emoji:'👽',rating:4.6,plays:870000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4p5/512x384.jpg',src:'https://html5.gamemonetize.co/a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4p5/',desc:'Defenda a Terra de invasores alienígenas!',descLong:'Caçador de Aliens é um jogo de tiro top-down frenético. Colete armas poderosas e elimine as frotas inimigas.',tags:['alien','tiro','invasão','ficção científica','defesa']},
  {id:'dragon-warrior',cat:'acao',badge:'top',name:'Dragon Warrior',namePT:'Guerreiro Dragão',emoji:'🐉',rating:4.9,plays:1450000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/g2h3i4j5k6l7m8n9o0p1q2r3s4t5u6v7/512x384.jpg',src:'https://html5.gamemonetize.co/g2h3i4j5k6l7m8n9o0p1q2r3s4t5u6v7/',desc:'Domine o poder dos dragões e conquiste reinos!',descLong:'Guerreiro Dragão é um RPG de ação épico. Monte dragões poderosos e conquiste reinos lendários.',tags:['dragão','rpg','magia','fantasia','guerreiro']},
  {id:'samurai-slash',cat:'acao',badge:'new',name:'Samurai Slash',namePT:'Samurai Veloz',emoji:'🗡️',rating:4.7,plays:830000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9/512x384.jpg',src:'https://html5.gamemonetize.co/m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9/',desc:'Seja o samurai mais rápido do Japão feudal!',descLong:'Samurai Veloz é um jogo de reflexo e habilidade. Corte inimigos com precisão e domine as artes marciais.',tags:['samurai','japão','espada','habilidade','reflexo']},
  {id:'cyber-ninja',cat:'acao',badge:'hot',name:'Cyber Ninja',namePT:'Ninja Cibernético',emoji:'🥷',rating:4.8,plays:1200000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/i2j3k4l5m6n7o8p9q0r1s2t3u4v5w6x7/512x384.jpg',src:'https://html5.gamemonetize.co/i2j3k4l5m6n7o8p9q0r1s2t3u4v5w6x7/',desc:'Ninja do futuro em missões de alta tecnologia!',descLong:'Ninja Cibernético mistura artes marciais com tecnologia futurista. Hackeie sistemas e elimine corporações corruptas em uma distopia cyberpunk.',tags:['cyberpunk','ninja','futuro','tecnologia','stealth']},
  {id:'pirates-clash',cat:'acao',name:'Pirates Clash',namePT:'Batalha Pirata',emoji:'🏴‍☠️',rating:4.5,plays:720000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/q6r7s8t9u0v1w2x3y4z5a6b7c8d9e0f1/512x384.jpg',src:'https://www.gamepix.com/play/pirates-clash/?sdk=1',desc:'Conquiste os sete mares nessa batalha pirata épica!',descLong:'Batalha Pirata coloca você no comando de um navio pirata temível. Afunde embarcações inimigas e expanda seu império marítimo.',tags:['pirata','navio','ação','aventura','mar']},
  {id:'robot-rampage',cat:'acao',name:'Robot Rampage',namePT:'Robô Destruidor',emoji:'🤖',rating:4.4,plays:590000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/w8x9y0z1a2b3c4d5e6f7g8h9i0j1k2l3/512x384.jpg',src:'https://www.gamepix.com/play/robot-rampage/?sdk=1',desc:'Controle um robô gigante e destrua tudo!',descLong:'Robô Destruidor é um jogo de ação caótico onde você pilota um robô colossal.',tags:['robô','destruição','ação','cidade','caos']},
  {id:'stickman-battle',cat:'acao',name:'Stickman Battle',namePT:'Batalha Stickman',emoji:'🙂',rating:4.2,plays:480000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/s6t7u8v9w0x1y2z3a4b5c6d7e8f9g0h1/512x384.jpg',src:'https://www.gamepix.com/play/stickman-battle/?sdk=1',desc:'Batalha épica de stickmen com física realista!',descLong:'Batalha Stickman combina física ragdoll com combate intenso.',tags:['stickman','batalha','física','ragdoll','luta']},
  {id:'commando-strike',cat:'acao',name:'Commando Strike',namePT:'Golpe Commando',emoji:'💂',rating:4.3,plays:560000,year:2023,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/c0d1e2f3g4h5i6j7k8l9m0n1o2p3q4r5/512x384.jpg',src:'https://html5.gamemonetize.co/c0d1e2f3g4h5i6j7k8l9m0n1o2p3q4r5/',desc:'Missão de elite: elimine os alvos com precisão!',descLong:'Golpe Commando é um jogo de ação militar com missões táticas.',tags:['militar','missão','tiro','stealth','commando']},

  // ══ CORRIDA (12) ══
  {id:'turbo-drift',cat:'corrida',badge:'hot',featured:true,name:'Turbo Drift',namePT:'Turbo Drift',emoji:'🏎️',rating:4.8,plays:1620000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/y8z9a0b1c2d3e4f5g6h7i8j9k0l1m2n3/512x384.jpg',src:'https://html5.gamemonetize.co/y8z9a0b1c2d3e4f5g6h7i8j9k0l1m2n3/',desc:'Drift pelas curvas e vença o campeonato mundial!',descLong:'Turbo Drift é o jogo de corrida mais viciante do NeonPlay. Com física de drift realista e carros customizáveis.',tags:['drift','carro','velocidade','corrida','turbo']},
  {id:'moto-race-pro',cat:'corrida',badge:'new',name:'Moto Race Pro',namePT:'Moto Race Pro',emoji:'🏍️',rating:4.6,plays:980000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9/512x384.jpg',src:'https://html5.gamemonetize.co/o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9/',desc:'Pilote motos potentes em pistas selvagens!',descLong:'Moto Race Pro oferece corridas de moto emocionantes em pistas variadas.',tags:['moto','corrida','velocidade','enduro','rally']},
  {id:'road-fury',cat:'corrida',badge:'top',name:'Road Fury',namePT:'Fúria na Estrada',emoji:'🚗',rating:4.7,plays:1350000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/e0f1g2h3i4j5k6l7m8n9o0p1q2r3s4t5/512x384.jpg',src:'https://www.gamepix.com/play/road-fury/?sdk=1',desc:'Sobreviva ao tráfego caótico nessa estrada louca!',descLong:'Fúria na Estrada é um jogo de sobrevivência em alta velocidade.',tags:['estrada','sobrevivência','tráfego','velocidade','carro']},
  {id:'police-chase',cat:'corrida',badge:'hot',name:'Police Chase',namePT:'Perseguição Policial',emoji:'🚔',rating:4.8,plays:1480000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/a8b9c0d1e2f3g4h5i6j7k8l9m0n1o2p3/512x384.jpg',src:'https://html5.gamemonetize.co/a8b9c0d1e2f3g4h5i6j7k8l9m0n1o2p3/',desc:'Fuja da polícia ou seja o detetive nas ruas!',descLong:'Perseguição Policial oferece dois modos: fuja da polícia ou seja o policial que caça os fugitivos.',tags:['policial','perseguição','fuga','carro','openworld']},
  {id:'highway-racer',cat:'corrida',badge:'top',name:'Highway Racer',namePT:'Corredor da Rodovia',emoji:'🛣️',rating:4.7,plays:1180000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/c8d9e0f1g2h3i4j5k6l7m8n9o0p1q2r3/512x384.jpg',src:'https://html5.gamemonetize.co/c8d9e0f1g2h3i4j5k6l7m8n9o0p1q2r3/',desc:'Ultrapasse centenas de carros na rodovia em alta velocidade!',descLong:'Corredor da Rodovia é um jogo de corrida endless pela autoestrada.',tags:['rodovia','ultrapassagem','velocidade','enduro','corrida']},
  {id:'space-rider',cat:'corrida',badge:'new',name:'Space Rider',namePT:'Piloto Espacial',emoji:'🚀',rating:4.7,plays:910000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/w6x7y8z9a0b1c2d3e4f5g6h7i8j9k0l1/512x384.jpg',src:'https://www.gamepix.com/play/space-rider/?sdk=1',desc:'Corrida intergaláctica em naves ultravelozes!',descLong:'Piloto Espacial leva a corrida para o espaço sideral.',tags:['espaço','nave','corrida','galáxia','futurista']},
  {id:'super-kart',cat:'corrida',name:'Super Kart',namePT:'Super Kart',emoji:'🏁',rating:4.5,plays:790000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/u6v7w8x9y0z1a2b3c4d5e6f7g8h9i0j1/512x384.jpg',src:'https://html5.gamemonetize.co/u6v7w8x9y0z1a2b3c4d5e6f7g8h9i0j1/',desc:'Corrida de kart com itens e power-ups malucos!',descLong:'Super Kart é o jogo de kart mais divertido da internet!',tags:['kart','itens','corrida','divertido','powerup']},
  {id:'formula-speed',cat:'corrida',name:'Formula Speed',namePT:'Fórmula Velocidade',emoji:'🏆',rating:4.6,plays:860000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7/512x384.jpg',src:'https://www.gamepix.com/play/formula-speed/?sdk=1',desc:'Pilote na Fórmula 1 em circuitos oficiais!',descLong:'Fórmula Velocidade simula com precisão as corridas de Fórmula 1.',tags:['f1','fórmula','circuito','corrida','piloto']},
  {id:'offroad-madness',cat:'corrida',name:'Offroad Madness',namePT:'Loucura Off-Road',emoji:'🚙',rating:4.4,plays:630000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8f9/512x384.jpg',src:'https://www.gamepix.com/play/offroad-madness/?sdk=1',desc:'SUVs potentes em terrenos impossíveis!',descLong:'Loucura Off-Road é um simulador de condução extrema.',tags:['offroad','4x4','terreno','aventura','suv']},
  {id:'boat-racing',cat:'corrida',name:'Boat Racing',namePT:'Corrida de Barcos',emoji:'🚤',rating:4.3,plays:540000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/g0h1i2j3k4l5m6n7o8p9q0r1s2t3u4v5/512x384.jpg',src:'https://html5.gamemonetize.co/g0h1i2j3k4l5m6n7o8p9q0r1s2t3u4v5/',desc:'Corridas de barcos em rios e lagos tropicais!',descLong:'Corrida de Barcos oferece emocionantes disputas aquáticas.',tags:['barco','água','corrida','náutico','velocidade']},
  {id:'city-taxi',cat:'corrida',name:'City Taxi Rush',namePT:'Táxi da Cidade',emoji:'🚕',rating:4.2,plays:490000,year:2023,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7/512x384.jpg',src:'https://html5.gamemonetize.co/m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7/',desc:'Seja o taxista mais rápido da cidade!',descLong:'Táxi da Cidade é um jogo de corrida urbana. Quanto mais rápido, maior a gorjeta!',tags:['táxi','cidade','trânsito','corrida','urban']},
  {id:'monster-truck',cat:'corrida',name:'Monster Truck',namePT:'Monster Truck',emoji:'🛻',rating:4.5,plays:750000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/s4t5u6v7w8x9y0z1a2b3c4d5e6f7g8h9/512x384.jpg',src:'https://www.gamepix.com/play/monster-truck/?sdk=1',desc:'Esmague carros com seu monster truck gigante!',descLong:'Monster Truck coloca você atrás do volante do maior truck do mundo.',tags:['monster','truck','destruição','acrobacia','gigante']},

  // ══ PUZZLE (12) ══
  {id:'jewel-crush',cat:'puzzle',badge:'hot',featured:true,name:'Jewel Crush',namePT:'Esmagamento de Joias',emoji:'💎',rating:4.9,plays:2100000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5/512x384.jpg',src:'https://html5.gamemonetize.co/i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5/',desc:'Combine joias e alcance pontuações épicas!',descLong:'Esmagamento de Joias é o match-3 mais viciante da internet! Faça combos explosivos e complete centenas de níveis.',tags:['match3','joia','combo','puzzle','colorido']},
  {id:'bubble-shooter',cat:'puzzle',badge:'top',name:'Bubble Shooter',namePT:'Estoura Bolhas',emoji:'🫧',rating:4.8,plays:1580000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/c6d7e8f9g0h1i2j3k4l5m6n7o8p9q0r1/512x384.jpg',src:'https://www.gamepix.com/play/bubble-shooter/?sdk=1',desc:'Estoure bolhas coloridas em combos incríveis!',descLong:'Estoura Bolhas é um dos jogos mais jogados do mundo!',tags:['bolhas','combo','colorido','clássico','casual']},
  {id:'2048-neon',cat:'puzzle',badge:'hot',name:'2048 Neon',namePT:'2048 Neon',emoji:'✨',rating:4.8,plays:1390000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/a6b7c8d9e0f1g2h3i4j5k6l7m8n9o0p1/512x384.jpg',src:'https://www.gamepix.com/play/2048-neon/?sdk=1',desc:'O clássico 2048 com efeitos neon impressionantes!',descLong:'2048 Neon moderniza o clássico jogo de números com visuais neon brilhantes.',tags:['2048','número','combinar','neon','clássico']},
  {id:'block-puzzle',cat:'puzzle',name:'Block Puzzle',namePT:'Quebra-Bloco',emoji:'🧱',rating:4.6,plays:890000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/y6z7a8b9c0d1e2f3g4h5i6j7k8l9m0n1/512x384.jpg',src:'https://www.gamepix.com/play/block-puzzle/?sdk=1',desc:'Encaixe blocos tetris em formas cada vez mais complexas!',descLong:'Quebra-Bloco é um puzzle de blocos altamente viciante.',tags:['bloco','tetris','grid','encaixe','puzzle']},
  {id:'slice-master',cat:'puzzle',badge:'new',name:'Slice Master',namePT:'Mestre do Corte',emoji:'🔪',rating:4.7,plays:970000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/w4x5y6z7a8b9c0d1e2f3g4h5i6j7k8l9/512x384.jpg',src:'https://html5.gamemonetize.co/w4x5y6z7a8b9c0d1e2f3g4h5i6j7k8l9/',desc:'Corte frutas e formas geométricas com precisão!',descLong:'Mestre do Corte combina reflexo com estratégia. 300+ fases.',tags:['corte','fruta','reflexo','física','arcade']},
  {id:'sudoku-master',cat:'puzzle',badge:'top',name:'Sudoku Master',namePT:'Mestre do Sudoku',emoji:'🔢',rating:4.7,plays:760000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7/512x384.jpg',src:'https://html5.gamemonetize.co/o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7/',desc:'Sudoku clássico com 1000+ puzzles únicos!',descLong:'Mestre do Sudoku oferece mais de 1000 puzzles em 4 níveis de dificuldade.',tags:['sudoku','lógica','número','raciocínio','clássico']},
  {id:'color-sort',cat:'puzzle',name:'Color Sort',namePT:'Ordenar Cores',emoji:'🎨',rating:4.6,plays:830000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/q2r3s4t5u6v7w8x9y0z1a2b3c4d5e6f7/512x384.jpg',src:'https://html5.gamemonetize.co/q2r3s4t5u6v7w8x9y0z1a2b3c4d5e6f7/',desc:'Organize as bolas coloridas nos tubos certos!',descLong:'Ordenar Cores é o puzzle de classificação mais relaxante.',tags:['cores','bolas','tubos','lógica','organizar']},
  {id:'mahjong-classic',cat:'puzzle',name:'Mahjong Classic',namePT:'Mahjong Clássico',emoji:'🀄',rating:4.5,plays:680000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/e8f9g0h1i2j3k4l5m6n7o8p9q0r1s2t3/512x384.jpg',src:'https://html5.gamemonetize.co/e8f9g0h1i2j3k4l5m6n7o8p9q0r1s2t3/',desc:'O clássico Mahjong com centenas de layouts!',descLong:'Mahjong Clássico com 300+ layouts únicos.',tags:['mahjong','tiles','clássico','oriental','relaxante']},
  {id:'word-connect',cat:'puzzle',badge:'new',name:'Word Connect',namePT:'Conecta Palavras',emoji:'📝',rating:4.4,plays:520000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/u4v5w6x7y8z9a0b1c2d3e4f5g6h7i8j9/512x384.jpg',src:'https://www.gamepix.com/play/word-connect/?sdk=1',desc:'Encontre palavras escondidas nas letras embaralhadas!',descLong:'Conecta Palavras desafia seu vocabulário com centenas de fases temáticas.',tags:['palavras','vocabulário','letras','português','quiz']},
  {id:'pipe-puzzle',cat:'puzzle',name:'Pipe Puzzle',namePT:'Puzzle de Canos',emoji:'🔧',rating:4.3,plays:410000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5/512x384.jpg',src:'https://html5.gamemonetize.co/k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5/',desc:'Gire os canos para fazer a água fluir!',descLong:'Puzzle de Canos com 200 níveis progressivos.',tags:['cano','água','lógica','rotação','plumber']},
  {id:'crossword-ptbr',cat:'puzzle',name:'Crossword PT-BR',namePT:'Palavras Cruzadas',emoji:'🔡',rating:4.5,plays:620000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/m0n1o2p3q4r5s6t7u8v9w0x1y2z3a4b5/512x384.jpg',src:'https://html5.gamemonetize.co/m0n1o2p3q4r5s6t7u8v9w0x1y2z3a4b5/',desc:'Palavras cruzadas em português com temas variados!',descLong:'Centenas de puzzles em português com dicas inteligentes.',tags:['palavras cruzadas','português','vocabulário','conhecimento','puzzle']},
  {id:'memory-cards',cat:'puzzle',name:'Memory Cards',namePT:'Jogo da Memória',emoji:'🃏',rating:4.2,plays:380000,year:2023,developer:'GamePix',thumb:'https://img.gamemonetize.com/g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3/512x384.jpg',src:'https://www.gamepix.com/play/memory-cards/?sdk=1',desc:'Treine sua memória encontrando os pares de cartas!',descLong:'Jogo da Memória digital com temas variados.',tags:['memória','cartas','pares','concentração','clássico']},

  // ══ ARCADE (12) ══
  {id:'pacman-remix',cat:'arcade',badge:'top',featured:true,name:'Pac-Man Remix',namePT:'Pac-Man Remix',emoji:'👻',rating:4.9,plays:2400000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/s2t3u4v5w6x7y8z9a0b1c2d3e4f5g6h7/512x384.jpg',src:'https://html5.gamemonetize.co/s2t3u4v5w6x7y8z9a0b1c2d3e4f5g6h7/',desc:'O lendário Pac-Man em versão moderna e neon!',descLong:'Pac-Man Remix traz o clássico de volta com gráficos neon.',tags:['pacman','clássico','labirinto','fantasma','retrô']},
  {id:'tetris-battle',cat:'arcade',badge:'top',name:'Tetris Battle',namePT:'Batalha Tetris',emoji:'🟦',rating:4.9,plays:2000000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/u2v3w4x5y6z7a8b9c0d1e2f3g4h5i6j7/512x384.jpg',src:'https://html5.gamemonetize.co/u2v3w4x5y6z7a8b9c0d1e2f3g4h5i6j7/',desc:'Tetris clássico com modo batalha online!',descLong:'Batalha Tetris reimagina o clássico mais amado da história dos videogames.',tags:['tetris','blocos','clássico','batalha','lógica']},
  {id:'snake-neon',cat:'arcade',badge:'hot',name:'Snake Neon',namePT:'Cobra Neon',emoji:'🐍',rating:4.8,plays:1720000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/y4z5a6b7c8d9e0f1g2h3i4j5k6l7m8n9/512x384.jpg',src:'https://html5.gamemonetize.co/y4z5a6b7c8d9e0f1g2h3i4j5k6l7m8n9/',desc:'A cobrinha clássica com efeitos neon incríveis!',descLong:'Cobra Neon moderniza o Snake com visuais neon brilhantes e ranking global.',tags:['cobra','snake','clássico','neon','crescer']},
  {id:'astro-dodge',cat:'arcade',badge:'hot',name:'Astro Dodge',namePT:'Desvio Astral',emoji:'☄️',rating:4.7,plays:1050000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/q0r1s2t3u4v5w6x7y8z9a0b1c2d3e4f5/512x384.jpg',src:'https://www.gamepix.com/play/astro-dodge/?sdk=1',desc:'Desvie de asteroides em velocidade máxima!',descLong:'Desvio Astral é um jogo de reflexo espacial ultra-rápido.',tags:['espaço','asteroide','desvio','reflexo','velocidade']},
  {id:'galaga-reborn',cat:'arcade',badge:'new',name:'Galaga Reborn',namePT:'Galaga Renascido',emoji:'🛸',rating:4.6,plays:780000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1/512x384.jpg',src:'https://html5.gamemonetize.co/e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1/',desc:'O clássico Galaga com gráficos e jogabilidade modernos!',descLong:'Galaga Renascido traz o shooter espacial dos anos 80 com gráficos HD.',tags:['galaga','shooter','espaço','retrô','nave']},
  {id:'dino-jump',cat:'arcade',badge:'new',name:'Dino Jump',namePT:'Pulo do Dino',emoji:'🦕',rating:4.6,plays:850000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/m8n9o0p1q2r3s4t5u6v7w8x9y0z1a2b3/512x384.jpg',src:'https://html5.gamemonetize.co/m8n9o0p1q2r3s4t5u6v7w8x9y0z1a2b3/',desc:'Faça o dinossauro saltar cada vez mais alto!',descLong:'Pulo do Dino é um jogo de saltos infinitos com dinossauro fofo.',tags:['dino','pulo','plataforma','infinito','casual']},
  {id:'space-invaders-x',cat:'arcade',name:'Space Invaders X',namePT:'Invasores do Espaço X',emoji:'👾',rating:4.7,plays:980000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3/512x384.jpg',src:'https://www.gamepix.com/play/space-invaders-x/?sdk=1',desc:'Defenda a Terra dos invasores em ondas infindáveis!',descLong:'Invasores do Espaço X reinventa o clássico arcade com boss battles épicas.',tags:['invasores','espaço','defesa','retrô','arcade']},
  {id:'flappy-bird-pro',cat:'arcade',name:'Flappy Bird Pro',namePT:'Pássaro Voador Pro',emoji:'🐦',rating:4.3,plays:640000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/o0p1q2r3s4t5u6v7w8x9y0z1a2b3c4d5/512x384.jpg',src:'https://www.gamepix.com/play/flappy-bird-pro/?sdk=1',desc:'Voe pelo maior tempo possível desviando de obstáculos!',descLong:'Pássaro Voador Pro é o jogo de tap mais viciante reformulado.',tags:['pássaro','tap','obstáculo','one-tap','casual']},
  {id:'breakout-neon',cat:'arcade',name:'Breakout Neon',namePT:'Quebre os Tijolos',emoji:'🏓',rating:4.5,plays:620000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/k8l9m0n1o2p3q4r5s6t7u8v9w0x1y2z3/512x384.jpg',src:'https://www.gamepix.com/play/breakout-neon/?sdk=1',desc:'Quebre tijolos neon com a bola e a raquete!',descLong:'Quebre os Tijolos é o Breakout reimaginado em neon.',tags:['breakout','tijolos','raquete','neon','bola']},
  {id:'frogger-3d',cat:'arcade',name:'Frogger 3D',namePT:'Sapo Saltitante 3D',emoji:'🐸',rating:4.4,plays:540000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/a4b5c6d7e8f9g0h1i2j3k4l5m6n7o8p9/512x384.jpg',src:'https://html5.gamemonetize.co/a4b5c6d7e8f9g0h1i2j3k4l5m6n7o8p9/',desc:'Ajude o sapinho a atravessar a rua perigosa!',descLong:'Sapo Saltitante 3D reinventa o Frogger clássico em perspectiva 3D.',tags:['sapo','travessia','clássico','3d','retrô']},
  {id:'pingpong-pro',cat:'arcade',name:'Ping Pong Pro',namePT:'Ping Pong Pro',emoji:'🏓',rating:4.5,plays:710000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1/512x384.jpg',src:'https://html5.gamemonetize.co/g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1/',desc:'Ping Pong com física realista e torneios online!',descLong:'Ping Pong Pro simula com precisão o tênis de mesa.',tags:['pingpong','tênis de mesa','raquete','esporte','2jogadores']},
  {id:'coin-rush',cat:'arcade',name:'Coin Rush',namePT:'Corrida de Moedas',emoji:'🪙',rating:4.3,plays:480000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/w2x3y4z5a6b7c8d9e0f1g2h3i4j5k6l7/512x384.jpg',src:'https://www.gamepix.com/play/coin-rush/?sdk=1',desc:'Colete o máximo de moedas antes que o tempo acabe!',descLong:'Corrida de Moedas é um frenético jogo de coleta com ranking global.',tags:['moeda','coleta','corrida','frenético','arcade']},

  // ══ ESPORTE (12) ══
  {id:'soccer-stars',cat:'esporte',badge:'hot',featured:true,name:'Soccer Stars',namePT:'Estrelas do Futebol',emoji:'⚽',rating:4.9,plays:2800000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9/512x384.jpg',src:'https://html5.gamemonetize.co/c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9/',desc:'O melhor jogo de futebol online grátis!',descLong:'Estrelas do Futebol é o simulador de futebol mais completo. Dispute ligas e copas mundiais.',tags:['futebol','soccer','time','liga','copa']},
  {id:'boxing-champions',cat:'esporte',badge:'hot',name:'Boxing Champions',namePT:'Campeões do Boxe',emoji:'🥊',rating:4.8,plays:1280000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9/512x384.jpg',src:'https://www.gamepix.com/play/boxing-champions/?sdk=1',desc:'Suba ao ringue e prove ser o melhor boxeador!',descLong:'Campeões do Boxe com controles intuitivos e física de golpe realista.',tags:['boxe','ringue','soco','campeão','luta']},
  {id:'surfing-waves',cat:'esporte',badge:'hot',name:'Surfing Waves',namePT:'Ondas do Surf',emoji:'🏄',rating:4.7,plays:1100000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/w0x1y2z3a4b5c6d7e8f9g0h1i2j3k4l5/512x384.jpg',src:'https://www.gamepix.com/play/surfing-waves/?sdk=1',desc:'Surfe ondas gigantes nas melhores praias do mundo!',descLong:'Ondas do Surf com física de ondas procedural. Nazaré, Pipeline e Bells Beach.',tags:['surf','onda','praia','manobra','brasil']},
  {id:'basketball-slam',cat:'esporte',name:'Basketball Slam',namePT:'Slam de Basquete',emoji:'🏀',rating:4.7,plays:1140000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/s0t1u2v3w4x5y6z7a8b9c0d1e2f3g4h5/512x384.jpg',src:'https://www.gamepix.com/play/basketball-slam/?sdk=1',desc:'Slam dunks incríveis e lances livres perfeitos!',descLong:'Slam de Basquete com física realista. Modo street basketball incluído.',tags:['basquete','slam','dunk','cesta','nba']},
  {id:'golf-master',cat:'esporte',badge:'top',name:'Golf Master',namePT:'Mestre do Golf',emoji:'⛳',rating:4.8,plays:1020000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/y2z3a4b5c6d7e8f9g0h1i2j3k4l5m6n7/512x384.jpg',src:'https://www.gamepix.com/play/golf-master/?sdk=1',desc:'18 holes de golf com física perfeita!',descLong:'Mestre do Golf é o simulador de golf mais preciso da web.',tags:['golf','tacada','buraco','hoyo','esporte']},
  {id:'pool-billiard',cat:'esporte',name:'Pool Billiard',namePT:'Sinuca Pro',emoji:'🎱',rating:4.7,plays:930000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/o8p9q0r1s2t3u4v5w6x7y8z9a0b1c2d3/512x384.jpg',src:'https://html5.gamemonetize.co/o8p9q0r1s2t3u4v5w6x7y8z9a0b1c2d3/',desc:'Jogue sinuca como um profissional!',descLong:'Sinuca Pro com física ultra-realista. Pool 8-ball, 9-ball e snooker.',tags:['sinuca','bilhar','pool','bola','esporte']},
  {id:'tennis-open',cat:'esporte',badge:'new',name:'Tennis Open',namePT:'Tênis Aberto',emoji:'🎾',rating:4.6,plays:820000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0x1/512x384.jpg',src:'https://html5.gamemonetize.co/i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0x1/',desc:'Vença Grand Slams e torne-se número 1 do mundo!',descLong:'Tênis Aberto com 4 superfícies e modo carreira completo.',tags:['tênis','grand slam','raquete','torneio','esporte']},
  {id:'skateboard-pro',cat:'esporte',name:'Skateboard Pro',namePT:'Skate Pro',emoji:'🛹',rating:4.5,plays:680000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/u0v1w2x3y4z5a6b7c8d9e0f1g2h3i4j5/512x384.jpg',src:'https://html5.gamemonetize.co/u0v1w2x3y4z5a6b7c8d9e0f1g2h3i4j5/',desc:'Faça manobras radicais e vença campeonatos de skate!',descLong:'Skate Pro com ollies, kickflips, grinds e modo freestyle.',tags:['skate','manobra','trick','rua','esporte radical']},
  {id:'volleyball-beach',cat:'esporte',name:'Beach Volleyball',namePT:'Vôlei de Praia',emoji:'🏐',rating:4.4,plays:570000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/k6l7m8n9o0p1q2r3s4t5u6v7w8x9y0z1/512x384.jpg',src:'https://www.gamepix.com/play/beach-volleyball/?sdk=1',desc:'Vôlei de praia 2x2 com saque, levantada e cortada!',descLong:'Vôlei de Praia simula o esporte olímpico brasileiro.',tags:['vôlei','praia','beach','brasil','esporte']},
  {id:'archery-master',cat:'esporte',badge:'new',name:'Archery Master',namePT:'Mestre do Arco',emoji:'🏹',rating:4.6,plays:760000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7/512x384.jpg',src:'https://html5.gamemonetize.co/a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7/',desc:'Mire, ajuste o vento e acerte o centro do alvo!',descLong:'Mestre do Arco com 50 fases progressivas.',tags:['arco','flecha','mira','precisão','alvo']},
  {id:'baseball-legend',cat:'esporte',name:'Baseball Legend',namePT:'Lenda do Baseball',emoji:'⚾',rating:4.3,plays:490000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/g4h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9/512x384.jpg',src:'https://html5.gamemonetize.co/g4h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9/',desc:'Tacadas perfeitas no melhor jogo de baseball online!',descLong:'Lenda do Baseball com física de bola realista.',tags:['baseball','taco','arremesso','home run','mlb']},
  {id:'pingpong-world',cat:'esporte',name:'Ping Pong World Cup',namePT:'Copa do Mundo Ping Pong',emoji:'🏆',rating:4.5,plays:630000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2f3/512x384.jpg',src:'https://www.gamepix.com/play/ping-pong-world-cup/?sdk=1',desc:'Dispute a Copa do Mundo de Ping Pong!',descLong:'Copa do Mundo Ping Pong com torneio épico. Defenda o Brasil!',tags:['pingpong','copa','torneio','mundial','esporte']},

  // ══ AVENTURA (12) ══
  {id:'dungeon-quest',cat:'aventura',badge:'hot',featured:true,name:'Dungeon Quest',namePT:'Missão na Masmorra',emoji:'🗡️',rating:4.8,plays:1680000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/m6n7o8p9q0r1s2t3u4v5w6x7y8z9a0b1/512x384.jpg',src:'https://html5.gamemonetize.co/m6n7o8p9q0r1s2t3u4v5w6x7y8z9a0b1/',desc:'Explore masmorras sombrias e colete tesouros épicos!',descLong:'Missão na Masmorra é um RPG com geração procedural. Enfrente os chefes mais poderosos!',tags:['masmorra','rpg','herói','tesouro','aventura']},
  {id:'dragon-realm',cat:'aventura',badge:'top',name:'Dragon Realm',namePT:'Reino dos Dragões',emoji:'🐲',rating:4.9,plays:1890000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/g2h3i4j5k6l7m8n9o0p1q2r3s4t5u6v7/512x384.jpg',src:'https://html5.gamemonetize.co/g2h3i4j5k6l7m8n9o0p1q2r3s4t5u6v7/',desc:'Monte seu dragão e conquiste reinos épicos!',descLong:'Reino dos Dragões é um RPG de aventura premium. O jogo mais completo do portal!',tags:['dragão','rpg','reino','cavaleiro','fantasia']},
  {id:'space-explorer',cat:'aventura',badge:'hot',name:'Space Explorer',namePT:'Explorador Espacial',emoji:'🌌',rating:4.8,plays:1450000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/e2f3g4h5i6j7k8l9m0n1o2p3q4r5s6t7/512x384.jpg',src:'https://html5.gamemonetize.co/e2f3g4h5i6j7k8l9m0n1o2p3q4r5s6t7/',desc:'Explore galáxias desconhecidas em busca de novos mundos!',descLong:'Explorador Espacial é um jogo de aventura intergaláctica.',tags:['espaço','galáxia','exploração','planeta','ficção científica']},
  {id:'lost-temple',cat:'aventura',badge:'top',name:'Lost Temple',namePT:'Templo Perdido',emoji:'🏛️',rating:4.7,plays:1020000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/y0z1a2b3c4d5e6f7g8h9i0j1k2l3m4n5/512x384.jpg',src:'https://html5.gamemonetize.co/y0z1a2b3c4d5e6f7g8h9i0j1k2l3m4n5/',desc:'Encontre os segredos do templo perdido!',descLong:'Templo Perdido ao estilo Indiana Jones. Resolva enigmas e encontre o artefato sagrado.',tags:['templo','enigma','armadilha','arqueologia','mistério']},
  {id:'pirate-treasure',cat:'aventura',badge:'new',name:'Pirate Treasure',namePT:'Tesouro Pirata',emoji:'💰',rating:4.6,plays:840000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/s8t9u0v1w2x3y4z5a6b7c8d9e0f1g2h3/512x384.jpg',src:'https://html5.gamemonetize.co/s8t9u0v1w2x3y4z5a6b7c8d9e0f1g2h3/',desc:'Embarque em busca do lendário tesouro pirata!',descLong:'Tesouro Pirata com múltiplas ilhas e tesouros secretos.',tags:['pirata','tesouro','ilha','mapa','aventura']},
  {id:'witch-adventure',cat:'aventura',badge:'new',name:'Witch Adventure',namePT:'Aventura da Bruxa',emoji:'🧙',rating:4.6,plays:810000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4p5/512x384.jpg',src:'https://www.gamepix.com/play/witch-adventure/?sdk=1',desc:'Voe em sua vassoura e desvende os mistérios mágicos!',descLong:'Aventura da Bruxa com feitiços poderosos e mundo mágico encantado.',tags:['bruxa','magia','vassoura','feitiço','fantasia']},
  {id:'jungle-explorer',cat:'aventura',name:'Jungle Explorer',namePT:'Explorador da Selva',emoji:'🌿',rating:4.5,plays:730000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/c2d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7/512x384.jpg',src:'https://www.gamepix.com/play/jungle-explorer/?sdk=1',desc:'Explore selvas perigosas em busca de artefatos raros!',descLong:'Explorador da Selva com 40 fases na selva amazônica.',tags:['selva','exploração','plataforma','amazônia','aventura']},
  {id:'forest-survival',cat:'aventura',name:'Forest Survival',namePT:'Sobrevivência na Floresta',emoji:'🌲',rating:4.5,plays:780000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1/512x384.jpg',src:'https://www.gamepix.com/play/forest-survival/?sdk=1',desc:'Sobreviva na floresta selvagem com poucos recursos!',descLong:'Sobrevivência na Floresta com crafting, construção e caça.',tags:['sobrevivência','floresta','crafting','construção','natureza']},
  {id:'deep-sea',cat:'aventura',name:'Deep Sea Quest',namePT:'Missão Abissal',emoji:'🐋',rating:4.4,plays:570000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/u8v9w0x1y2z3a4b5c6d7e8f9g0h1i2j3/512x384.jpg',src:'https://www.gamepix.com/play/deep-sea-quest/?sdk=1',desc:'Explore as profundezas do oceano em busca de mistérios!',descLong:'Missão Abissal com submarino e criaturas marinhas raras.',tags:['oceano','submarino','profundeza','mistério','marinha']},
  {id:'time-travel',cat:'aventura',name:'Time Travel',namePT:'Viagem no Tempo',emoji:'⏰',rating:4.5,plays:690000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/q6r7s8t9u0v1w2x3y4z5a6b7c8d9e0f1/512x384.jpg',src:'https://html5.gamemonetize.co/q6r7s8t9u0v1w2x3y4z5a6b7c8d9e0f1/',desc:'Viaje entre épocas históricas resolvendo paradoxos!',descLong:'Viagem no Tempo com Egito Antigo, Roma Clássica e futuro.',tags:['tempo','história','paradoxo','aventura','ficção']},
  {id:'castle-siege',cat:'aventura',name:'Castle Siege',namePT:'Cerco ao Castelo',emoji:'🏰',rating:4.4,plays:620000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/i4j5k6l7m8n9o0p1q2r3s4t5u6v7w8x9/512x384.jpg',src:'https://www.gamepix.com/play/castle-siege/?sdk=1',desc:'Conquiste castelos medievais em batalhas épicas!',descLong:'Cerco ao Castelo medieval com 30 missões históricas.',tags:['castelo','medieval','cerco','exército','estratégia']},
  {id:'mountain-climber',cat:'aventura',name:'Mountain Climber',namePT:'Escalador de Montanhas',emoji:'🏔️',rating:4.3,plays:420000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/k4l5m6n7o8p9q0r1s2t3u4v5w6x7y8z9/512x384.jpg',src:'https://html5.gamemonetize.co/k4l5m6n7o8p9q0r1s2t3u4v5w6x7y8z9/',desc:'Escale montanhas impossíveis com destreza!',descLong:'Escalador de Montanhas com gestão de energia e desafios de clima.',tags:['montanha','escalada','aventura','natureza','habilidade']},

  // ══ TIRO (10) ══
  {id:'zombie-shooter',cat:'tiro',badge:'top',name:'Zombie Shooter',namePT:'Mata Zumbis',emoji:'🧟',rating:4.9,plays:1950000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/c0d1e2f3g4h5i6j7k8l9m0n1o2p3q4r5/512x384.jpg',src:'https://html5.gamemonetize.co/c0d1e2f3g4h5i6j7k8l9m0n1o2p3q4r5/',desc:'Elimine hordas de zumbis em modo survival!',descLong:'Mata Zumbis é o survival shooter mais popular do NeonPlay.',tags:['zumbi','survival','tiro','horda','apocalipse']},
  {id:'sniper-elite',cat:'tiro',badge:'hot',name:'Sniper Elite',namePT:'Franco-Atirador Elite',emoji:'🎯',rating:4.8,plays:1520000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/w8x9y0z1a2b3c4d5e6f7g8h9i0j1k2l3/512x384.jpg',src:'https://html5.gamemonetize.co/w8x9y0z1a2b3c4d5e6f7g8h9i0j1k2l3/',desc:'Seja o sniper mais preciso do mundo!',descLong:'Franco-Atirador Elite com 40 missões táticas globais.',tags:['sniper','tiro','precisão','missão','atirador']},
  {id:'space-shooter',cat:'tiro',badge:'top',name:'Space Shooter',namePT:'Atirador Espacial',emoji:'🚀',rating:4.8,plays:1340000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/u6v7w8x9y0z1a2b3c4d5e6f7g8h9i0j1/512x384.jpg',src:'https://html5.gamemonetize.co/u6v7w8x9y0z1a2b3c4d5e6f7g8h9i0j1/',desc:'Destrua frotas inimigas no espaço sideral!',descLong:'Atirador Espacial é um shoot em up vertical clássico com gráficos modernos.',tags:['espaço','nave','atirador','galáxia','shootemup']},
  {id:'fps-combat',cat:'tiro',badge:'new',name:'FPS Combat',namePT:'Combate FPS',emoji:'🔫',rating:4.7,plays:1380000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9/512x384.jpg',src:'https://www.gamepix.com/play/fps-combat/?sdk=1',desc:'FPS de ação intensa com multiplayer online!',descLong:'Combate FPS com arsenal extenso e matchmaking inteligente.',tags:['fps','tiro','multiplayer','arma','combate']},
  {id:'turret-defense',cat:'tiro',badge:'hot',name:'Turret Defense',namePT:'Defesa de Torretas',emoji:'🏗️',rating:4.7,plays:1100000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/i2j3k4l5m6n7o8p9q0r1s2t3u4v5w6x7/512x384.jpg',src:'https://html5.gamemonetize.co/i2j3k4l5m6n7o8p9q0r1s2t3u4v5w6x7/',desc:'Construa torretas e defenda sua base de invasores!',descLong:'Defesa de Torretas mistura tower defense com ação de tiro.',tags:['torretas','defesa','tower-defense','estratégia','tiro']},
  {id:'gunslinger',cat:'tiro',badge:'new',name:'Gunslinger',namePT:'Pistoleiro',emoji:'🤠',rating:4.6,plays:820000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9/512x384.jpg',src:'https://html5.gamemonetize.co/o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9/',desc:'Duelos de faroeste no Velho Oeste!',descLong:'Pistoleiro com duelos e missões de caça-recompensa.',tags:['faroeste','duelo','pistola','cowboy','oeste']},
  {id:'bow-master',cat:'tiro',name:'Bow Master',namePT:'Mestre do Arco de Combate',emoji:'🏹',rating:4.5,plays:710000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/s6t7u8v9w0x1y2z3a4b5c6d7e8f9g0h1/512x384.jpg',src:'https://www.gamepix.com/play/bow-master/?sdk=1',desc:'Derrote inimigos com sua pontaria lendária!',descLong:'Mestre do Arco de Combate com física 2D realista e 100 fases.',tags:['arco','flecha','física','precisão','tiro']},
  {id:'laser-cannon',cat:'tiro',name:'Laser Cannon',namePT:'Canhão Laser',emoji:'⚡',rating:4.4,plays:590000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/y8z9a0b1c2d3e4f5g6h7i8j9k0l1m2n3/512x384.jpg',src:'https://www.gamepix.com/play/laser-cannon/?sdk=1',desc:'Destrua alvos com disparos de canhão laser preciso!',descLong:'Canhão Laser com 150 puzzles físicos desafiadores.',tags:['laser','canhão','física','reflexo','tiro']},
  {id:'nerf-battle',cat:'tiro',name:'Nerf Battle',namePT:'Batalha Nerf',emoji:'🎪',rating:4.4,plays:660000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7/512x384.jpg',src:'https://www.gamepix.com/play/nerf-battle/?sdk=1',desc:'Batalhas épicas com armas Nerf no playground!',descLong:'Batalha Nerf com arenas coloridas. Perfeito para todas as idades!',tags:['nerf','batalha','casual','arena','tiro']},
  {id:'tower-gun',cat:'tiro',name:'Tower Gun',namePT:'Artilheiro da Torre',emoji:'🏰',rating:4.3,plays:480000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/e0f1g2h3i4j5k6l7m8n9o0p1q2r3s4t5/512x384.jpg',src:'https://www.gamepix.com/play/tower-gun/?sdk=1',desc:'Defenda sua torre abatendo todos os invasores!',descLong:'Artilheiro da Torre com cavaleiros, catapultas e dragões.',tags:['torre','defesa','canhão','medieval','tiro']},

  // ══ ESTRATÉGIA (10) ══
  {id:'kingdom-rush',cat:'estrategia',badge:'top',name:'Kingdom Rush',namePT:'Corrida do Reino',emoji:'🏰',rating:4.9,plays:1900000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/s4t5u6v7w8x9y0z1a2b3c4d5e6f7g8h9/512x384.jpg',src:'https://html5.gamemonetize.co/s4t5u6v7w8x9y0z1a2b3c4d5e6f7g8h9/',desc:'O mais clássico e amado tower defense medieval!',descLong:'Corrida do Reino defende seu reino contra orcs, trolls e dragões.',tags:['medieval','torres','defesa','reino','orcs']},
  {id:'empire-builder',cat:'estrategia',badge:'hot',name:'Empire Builder',namePT:'Construtor de Impérios',emoji:'👑',rating:4.9,plays:1750000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/a8b9c0d1e2f3g4h5i6j7k8l9m0n1o2p3/512x384.jpg',src:'https://html5.gamemonetize.co/a8b9c0d1e2f3g4h5i6j7k8l9m0n1o2p3/',desc:'Construa e gerencie seu próprio império histórico!',descLong:'Construtor de Impérios é um 4X strategy game. Diplomacia, comércio e guerras épicas!',tags:['império','estratégia','construção','conquista','4x']},
  {id:'city-builder',cat:'estrategia',badge:'hot',name:'City Builder',namePT:'Construtor de Cidades',emoji:'🏙️',rating:4.8,plays:1420000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7/512x384.jpg',src:'https://html5.gamemonetize.co/m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7/',desc:'Construa e administre a metrópole dos seus sonhos!',descLong:'Construtor de Cidades é um simulador urbano completo com eventos aleatórios.',tags:['cidade','construção','simulador','gestão','urbano']},
  {id:'chess-master',cat:'estrategia',badge:'top',name:'Chess Master',namePT:'Xadrez Master',emoji:'♟️',rating:4.8,plays:1200000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8f9/512x384.jpg',src:'https://www.gamepix.com/play/chess-master/?sdk=1',desc:'Xadrez clássico com IA adaptativa e análise!',descLong:'Xadrez Master com 10 níveis de IA, análise de partidas e puzzles.',tags:['xadrez','chess','estratégia','IA','tabuleiro']},
  {id:'plant-vs-monsters',cat:'estrategia',name:'Plants vs Monsters',namePT:'Plantas vs Monstros',emoji:'🌻',rating:4.7,plays:1080000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/c8d9e0f1g2h3i4j5k6l7m8n9o0p1q2r3/512x384.jpg',src:'https://www.gamepix.com/play/plants-vs-monsters/?sdk=1',desc:'Defenda seu jardim com plantas poderosas!',descLong:'Plantas vs Monstros com dezenas de plantas desbloqueáveis.',tags:['plantas','monstros','defesa','jardim','estratégia']},
  {id:'tower-defense-pro',cat:'estrategia',badge:'new',name:'Tower Defense Pro',namePT:'Tower Defense Pro',emoji:'🏗️',rating:4.7,plays:950000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/g0h1i2j3k4l5m6n7o8p9q0r1s2t3u4v5/512x384.jpg',src:'https://html5.gamemonetize.co/g0h1i2j3k4l5m6n7o8p9q0r1s2t3u4v5/',desc:'O tower defense mais estratégico e viciante!',descLong:'Tower Defense Pro com 30 tipos de torres e modo infinito.',tags:['tower defense','torres','estratégia','ondas','defesa']},
  {id:'war-strategy',cat:'estrategia',name:'War Strategy',namePT:'Estratégia de Guerra',emoji:'⚔️',rating:4.6,plays:780000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/w6x7y8z9a0b1c2d3e4f5g6h7i8j9k0l1/512x384.jpg',src:'https://www.gamepix.com/play/war-strategy/?sdk=1',desc:'Comande exércitos em batalhas históricas épicas!',descLong:'Estratégia de Guerra recria batalhas históricas icônicas.',tags:['guerra','exército','história','batalha','comando']},
  {id:'merge-master',cat:'estrategia',badge:'new',name:'Merge Master',namePT:'Mestre da Fusão',emoji:'🔮',rating:4.6,plays:870000,year:2024,developer:'GameMonetize',thumb:'https://img.gamemonetize.com/y6z7a8b9c0d1e2f3g4h5i6j7k8l9m0n1/512x384.jpg',src:'https://html5.gamemonetize.co/y6z7a8b9c0d1e2f3g4h5i6j7k8l9m0n1/',desc:'Combine unidades para criar exércitos poderosos!',descLong:'Mestre da Fusão é um idle strategy único. Combine soldados e domine o campo de batalha.',tags:['merge','fusão','idle','exército','estratégia']},
  {id:'strategic-minds',cat:'estrategia',name:'Strategic Minds',namePT:'Mentes Estratégicas',emoji:'🧠',rating:4.5,plays:650000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5/512x384.jpg',src:'https://www.gamepix.com/play/strategic-minds/?sdk=1',desc:'Puzzles de estratégia para mentes brilhantes!',descLong:'Mentes Estratégicas com xadrez, Go e puzzles de lógica dedutiva.',tags:['lógica','estratégia','puzzle','cérebro','raciocínio']},
  {id:'resource-rush',cat:'estrategia',name:'Resource Rush',namePT:'Corrida por Recursos',emoji:'⛏️',rating:4.4,plays:560000,year:2024,developer:'GamePix',thumb:'https://img.gamemonetize.com/o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7/512x384.jpg',src:'https://www.gamepix.com/play/resource-rush/?sdk=1',desc:'Colete recursos, construa e vença a corrida econômica!',descLong:'Corrida por Recursos é um RTS econômico. Mine, construa e conquiste.',tags:['recursos','mineração','economia','rts','estratégia']},
];
