/**
/** NeonPlay v10 — games-data.js | 129 jogos 100% GamePix reais */
 * JOGOS REAIS — 100% GamePix (slugs verificados ao vivo)
 * Zero URLs inventadas. Todos os iframes funcionam.
 */
'use strict';

const CATEGORIES_DATA = [
  { id:'acao',       name:'Ação',          nameSEO:'Jogos de Ação',              emoji:'⚔️',  color:'#ff6b7a', gradient:'135deg,#ff6b7a,#c0392b', desc:'Os melhores jogos de ação HTML5 grátis. Lute, destrua e vença inimigos direto no navegador.' },
  { id:'corrida',    name:'Corrida',        nameSEO:'Jogos de Corrida',           emoji:'🏎️',  color:'#ffb628', gradient:'135deg,#ffb628,#e67e22', desc:'Sinta a adrenalina com os melhores jogos de corrida online grátis.' },
  { id:'puzzle',     name:'Puzzle',         nameSEO:'Jogos de Puzzle',            emoji:'🧩',  color:'#00e5ff', gradient:'135deg,#00e5ff,#0097a7', desc:'Desafie seu cérebro com os melhores jogos de puzzle online. Grátis, sem download.' },
  { id:'arcade',     name:'Arcade',         nameSEO:'Jogos de Arcade',            emoji:'🕹️',  color:'#b8b3fe', gradient:'135deg,#b8b3fe,#7c4dff', desc:'Clássicos do arcade modernizados. Jogos retrô e divertidos para jogar agora grátis.' },
  { id:'esporte',    name:'Esporte',        nameSEO:'Jogos de Esporte',           emoji:'⚽',  color:'#00ff88', gradient:'135deg,#00ff88,#00b894', desc:'Futebol, basquete, tênis e muito mais! Os melhores jogos de esporte online grátis.' },
  { id:'aventura',   name:'Aventura',       nameSEO:'Jogos de Aventura',          emoji:'🗺️',  color:'#fdcb6e', gradient:'135deg,#fdcb6e,#e17055', desc:'Explore mundos incríveis nos melhores jogos de aventura HTML5 online grátis.' },
  { id:'tiro',       name:'Tiro',           nameSEO:'Jogos de Tiro',              emoji:'🎯',  color:'#ff2d78', gradient:'135deg,#ff2d78,#a00037', desc:'Os melhores jogos de tiro online grátis. Mire, atire e domine o campo de batalha!' },
  { id:'estrategia', name:'Estratégia',     nameSEO:'Jogos de Estratégia',        emoji:'♟️',  color:'#74b9ff', gradient:'135deg,#74b9ff,#0984e3', desc:'Planeje, construa e conquiste! Os melhores jogos de estratégia online grátis.' },
  { id:'meninas',    name:'Meninas',        nameSEO:'Jogos de Meninas',           emoji:'👗',  color:'#fd79a8', gradient:'135deg,#fd79a8,#e84393', desc:'Os melhores jogos de meninas online grátis! Moda, maquiagem, culinária e muito mais.' },
  { id:'casual',     name:'Casual',         nameSEO:'Jogos Casuais',              emoji:'🎈',  color:'#55efc4', gradient:'135deg,#55efc4,#00b894', desc:'Jogos casuais divertidos para relaxar. Fáceis de jogar, impossíveis de parar!' },
  { id:'2jogadores', name:'2 Jogadores',    nameSEO:'Jogos para 2 Jogadores',     emoji:'👥',  color:'#a29bfe', gradient:'135deg,#a29bfe,#6c5ce7', desc:'Os melhores jogos para 2 jogadores online grátis. Jogue com amigos no mesmo teclado!' },
];

function getCategoryData(id){
  if(!id||id==='all') return {id:'all',name:'Todos',emoji:'🎮',color:'#00e5ff',gradient:'135deg,#00e5ff,#7c4dff',desc:'Todos os jogos grátis do NeonPlay.'};
  return CATEGORIES_DATA.find(c=>c.id===id)||{id,name:id,emoji:'🎮',color:'#00e5ff',gradient:'135deg,#00e5ff,#7c4dff',desc:''};
}
function getGameCount(cat){ return(!cat||cat==='all')?GAMES_DB.length:GAMES_DB.filter(g=>g.cat===cat).length; }
function getGameById(id){ return GAMES_DB.find(g=>g.id===id)||null; }
function searchGames(q){ const lq=q.toLowerCase(); return GAMES_DB.filter(g=>(g.namePT||g.name).toLowerCase().includes(lq)||(g.tags||[]).some(t=>t.includes(lq))); }
function getFeaturedGames(){ return GAMES_DB.filter(g=>g.featured).slice(0,6); }
function getTopGames(n=10){ return[...GAMES_DB].sort((a,b)=>b.plays-a.plays).slice(0,n); }
function getRelatedGames(game,n=6){ return GAMES_DB.filter(g=>g.id!==game.id&&g.cat===game.cat).sort((a,b)=>b.plays-a.plays).slice(0,n); }
function getGameBySlug(slug){
  if(!slug) return null;
  const byId=GAMES_DB.find(g=>g.id===slug); if(byId) return byId;
  const norm=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  return GAMES_DB.find(g=>norm(g.namePT)===norm(slug)||norm(g.name)===norm(slug))||null;
}

// ─────────────────────────────────────────────────────────────
// HELPERS DE PROVIDER
//
// gp(slug)  → GamePix  — usa SID de NP_CONFIG.providers.gamepix.sid
// gm(id)    → GameMonetize — use com IDs reais do dashboard
//
// Para resiliência multi-provider, adicione o campo fallbacks:
//   { ...gp('moto-x3m-spooky'), fallbacks:[{provider:'gamemonetize', gmId:'REAL_ID'}] }
//
// ─────────────────────────────────────────────────────────────
// CONSOLE DO BROWSER — comandos disponíveis:
//
//   NP_Diagnostics.validateAll()      ← relatório completo (sem rede)
//   NP_Diagnostics.testGame('slug')   ← inspeciona 1 jogo
//   NP_Diagnostics.probeAll(20)       ← testa 20 jogos via iframe real
//   NP_Diagnostics.cacheStats()       ← status do cache de verificação
//   NP_Diagnostics.clearCache()       ← limpa cache para re-teste
//   NP_Diagnostics.listByProvider()   ← contagem por provider
//
//   GameVerificationCache.stats()     ← resumo localStorage
//   GameVerificationCache.clear()     ← limpa cache
//   SmartFallback.getNext(game)       ← próximo jogo da categoria
// ─────────────────────────────────────────────────────────────

const gp = (slug, overrideThumb) => ({
  // src é fallback sem SID — buildGameUrl() usa NP_CONFIG.providers.gamepix.sid em runtime
  src:      `https://www.gamepix.com/play/${slug}/?sdk=1`,
  slug:     slug,
  provider: 'gamepix',
  thumb: overrideThumb || `https://img.gamepix.com/games/${slug}/cover/${slug}.png?w=512&ar=4:3`,
});

// Helper GameMonetize — use quando tiver IDs reais do dashboard GameMonetize
const gm = (id, overrideThumb) => ({
  src:      `https://html5.gamemonetize.co/${id}/`,
  gmId:     id,
  provider: 'gamemonetize',
  thumb: overrideThumb || `https://img.gamemonetize.com/${id}/512x384.jpg`,
});

const GAMES_DB=[

  // ══ AÇÃO (13) ══
  {id:'stickman-street-fighting',cat:'acao',badge:'hot',featured:true,name:'Stickman Street Fighting',namePT:'Briga de Rua Stickman',emoji:'👊',rating:4.7,plays:1200000,year:2024,...gp('stickman-street-fighting'),desc:'Lute nas ruas com os stickmen mais brutais!',descLong:'Briga de Rua Stickman é um beat\'em up de ação intensa. Enfrente gangues de stickmen em ruas perigosas, use combos devastadores e desbloqueie novas habilidades. Cada fase aumenta o desafio com inimigos mais fortes e arenas maiores.',tags:['briga','stickman','rua','luta','combate']},
  {id:'red-stickman-fight',cat:'acao',badge:'new',name:'Red Stickman vs Stick',namePT:'Stickman Vermelho',emoji:'🥋',rating:4.6,plays:980000,year:2024,...gp('red-stickman-fighting-stick'),desc:'O stickman vermelho enfrenta hordas de inimigos!',descLong:'Stickman Vermelho em Ação coloca você no controle de um guerreiro stickman ágil. Lute contra ondas de inimigos em combate fluido e frenético com pulos, socos e chutes poderosos.',tags:['stickman','vermelho','luta','ação','horda']},
  {id:'superhero-league',cat:'acao',badge:'top',featured:true,name:'The Superhero League',namePT:'Liga dos Super-Heróis',emoji:'🦸',rating:4.8,plays:1450000,year:2024,...gp('the-superhero-league'),desc:'Monte seu time de heróis e salve o mundo!',descLong:'A Liga dos Super-Heróis é um jogo de ação épico. Recrute heróis com poderes únicos, forme equipes estratégicas e enfrente vilões cada vez mais poderosos em batalhas espetaculares.',tags:['herói','super','liga','ação','equipe']},
  {id:'stickman-archero',cat:'acao',name:'Stickman Archero Fight',namePT:'Arqueiro Stickman',emoji:'🏹',rating:4.5,plays:870000,year:2024,...gp('stickman-archero-fight'),desc:'Atire flechas e elimine todos os monstros!',descLong:'Arqueiro Stickman é um roguelite de ação viciante. Controle seu arqueiro por calabouços cheios de monstros, colete power-ups e evolua suas habilidades a cada rodada.',tags:['arqueiro','stickman','roguelite','flechas','ação']},
  {id:'stickman-mega-brawl',cat:'acao',name:'Stickman Mega Brawl',namePT:'Stickman Lutador Épico',emoji:'💥',rating:4.6,plays:920000,year:2024,...gp('stickman-fighter-mega-brawl'),desc:'Batalha épica de stickmen com golpes devastadores!',descLong:'Stickman Lutador Épico traz combate corpo a corpo com física realista. Domine combos poderosos e derrote todos os oponentes no torneio definitivo dos stickmen.',tags:['stickman','luta','brawl','combate','torneio']},
  {id:'karate-bodybuilder',cat:'acao',name:'Bodybuilder Karate',namePT:'Karatê do Fortão',emoji:'🥊',rating:4.4,plays:760000,year:2024,...gp('bodybuilder-karate-fighting'),desc:'Karatê com musculação: golpes brutais garantidos!',descLong:'Karatê do Fortão mistura artes marciais com humor. Controle um bodybuilder ágil e derrote oponentes com socos, chutes e golpes especiais em arenas variadas.',tags:['karatê','luta','musculação','artes marciais','combate']},
  {id:'narrow-one',cat:'acao',badge:'hot',name:'Narrow One',namePT:'Narrow One',emoji:'🏹',rating:4.8,plays:1380000,year:2024,...gp('narrow-one'),desc:'Capture a bandeira com seu arco e flecha!',descLong:'Narrow One é um shooter multiplayer de captura de bandeira com arcos medievais. Entre em batalhas rápidas, mire e atire com precisão para proteger sua bandeira e capturar a do inimigo.',tags:['arco','multijogador','captura','medieval','competitivo']},
  {id:'battle-arena',cat:'acao',badge:'new',name:'Battle Arena',namePT:'Arena de Batalha',emoji:'⚔️',rating:4.5,plays:840000,year:2024,...gp('battle-arena'),desc:'Entre na arena e elimine todos os oponentes!',descLong:'Arena de Batalha é um jogo de ação onde você luta contra inimigos em rounds progressivos. Escolha suas armas, use o ambiente a seu favor e sobreviva até ser o último de pé.',tags:['arena','batalha','sobrevivência','ação','luta']},
  {id:'brutal-defender',cat:'acao',name:'Brutal Defender',namePT:'Defensor Brutal',emoji:'🛡️',rating:4.5,plays:790000,year:2024,...gp('brutal-defender'),desc:'Defenda sua posição contra hordas inimigas!',descLong:'Defensor Brutal coloca você como o último bastião contra ondas de inimigos. Use espadas, magias e habilidades especiais para manter os invasores afastados.',tags:['defesa','horda','ação','herói','ondas']},
  {id:'gang-city-fight',cat:'acao',name:'Gang Street Fight',namePT:'Gangues da Cidade',emoji:'🌆',rating:4.4,plays:680000,year:2024,...gp('city-of-gang-street-fighting'),desc:'Domine as ruas e elimine as gangues rivais!',descLong:'Gangues da Cidade é um beat\'em up urbano onde você percorre bairros perigosos enfrentando membros de gangues. Lute seu caminho até o chefão e limpe as ruas.',tags:['gangue','rua','cidade','beat-em-up','luta']},
  {id:'merge-battle',cat:'acao',badge:'top',name:'Merge Battle Tactics',namePT:'Tática Merge',emoji:'🔮',rating:4.7,plays:1050000,year:2024,...gp('merge-battle-tactics'),desc:'Combine guerreiros e vença batalhas épicas!',descLong:'Tática Merge combina estratégia com ação. Arraste e combine unidades para criar guerreiros mais poderosos e envie-os para batalha em mapas progressivos.',tags:['merge','batalha','tática','combinar','estratégia']},
  {id:'gladiators-merge',cat:'acao',name:'Gladiators Merge',namePT:'Gladiadores Merge',emoji:'🏛️',rating:4.6,plays:890000,year:2024,...gp('gladiators-merge-and-fight'),desc:'Combine gladiadores e domine o Coliseu!',descLong:'Gladiadores Merge traz o Coliseu Romano ao seu navegador. Combine gladiadores para criar campeões e envie-os para combates épicos.',tags:['gladiador','coliseu','merge','romano','luta']},
  {id:'turbo-dismounting',cat:'acao',badge:'hot',name:'Turbo Dismounting',namePT:'Turbo Desmontagem',emoji:'💀',rating:4.8,plays:1600000,year:2024,...gp('turbo-dismounting'),desc:'Cause o maior acidente possível e marque pontos!',descLong:'Turbo Desmontagem é o simulador de acidentes mais hilário! Posicione seu boneco, escolha o veículo e cause o maior acidente para pontuar. Física ragdoll ultra-realista.',tags:['acidente','física','ragdoll','humor','caos']},

  // ══ CORRIDA (12) ══
  {id:'moto-x3m-spooky',cat:'corrida',badge:'hot',featured:true,name:'Moto X3M Spooky Land',namePT:'Moto X3M Halloween',emoji:'🏍️',rating:4.9,plays:2200000,year:2024,...gp('moto-x3m-spooky-land'),desc:'Pilote sua moto em pistas assombradas de Halloween!',descLong:'Moto X3M Halloween é a versão mais assustadora do jogo de motos mais amado. Supere obstáculos perigosos em cenários sombrios e termine cada fase no menor tempo possível.',tags:['moto','halloween','acrobacia','corrida','x3m']},
  {id:'slope-3d',cat:'corrida',badge:'top',name:'Slope Racing 3D',namePT:'Slope 3D',emoji:'⛷️',rating:4.8,plays:1850000,year:2024,...gp('slope-racing-3d'),desc:'Desça rampas em 3D na maior velocidade possível!',descLong:'Slope 3D é um jogo de corrida vertiginoso. Controle uma bola em alta velocidade por rampas íngremes com obstáculos, curvas e saltos. Requer reflexos de aço.',tags:['slope','3d','velocidade','rampa','reflexo']},
  {id:'madalin-stunt',cat:'corrida',badge:'hot',name:'Madalin Stunt Cars 2',namePT:'Madalin Acrobacia',emoji:'🚗',rating:4.8,plays:1750000,year:2024,...gp('agame-stunt-car'),desc:'Faça acrobacias incríveis com carros esportivos!',descLong:'Madalin Acrobacia é um dos melhores jogos de carro. Explore arenas enormes em mundo aberto, faça saltos, drifts e acrobacias com dezenas de carros de luxo.',tags:['carro','acrobacia','mundo aberto','esportivo','livre']},
  {id:'madalin-multiplayer',cat:'corrida',badge:'new',name:'Madalin Cars Multiplayer',namePT:'Madalin Multiplayer',emoji:'🏁',rating:4.7,plays:1400000,year:2024,...gp('madalin-cars-multiplayer'),desc:'Corrida e acrobacias em multiplayer real!',descLong:'Madalin Multiplayer leva as acrobacias para o modo online. Jogue com outros jogadores do mundo todo e mostre suas habilidades ao volante.',tags:['multiplayer','carro','online','acrobacia','corrida']},
  {id:'mr-racer',cat:'corrida',name:'Mr Racer',namePT:'Mr. Racer',emoji:'🏎️',rating:4.6,plays:1100000,year:2024,...gp('mr-racer-car-racing-game'),desc:'Ultrapasse carros na rodovia em alta velocidade!',descLong:'Mr. Racer é um jogo de corrida de estrada clássico. Vire entre o tráfego intenso, colete moedas e melhore seu veículo progressivamente.',tags:['corrida','rodovia','ultrapassagem','carros','velocidade']},
  {id:'car-crash',cat:'corrida',name:'Car Crash Test',namePT:'Teste de Colisão',emoji:'💥',rating:4.6,plays:1050000,year:2024,...gp('car-crash-test'),desc:'Simule colisões épicas com física realista!',descLong:'Teste de Colisão é o simulador de acidentes mais detalhado. Escolha veículos, posicione-os e observe a física de destruição em câmera lenta.',tags:['colisão','física','destruição','simulador','carro']},
  {id:'superhero-race',cat:'corrida',badge:'new',name:'Superhero Race',namePT:'Corrida de Heróis',emoji:'🦸',rating:4.5,plays:890000,year:2024,...gp('superhero-race'),desc:'Corra como um super-herói nas pistas mais loucas!',descLong:'Corrida de Heróis é uma corrida de plataforma frenética. Use super-poderes para se mover mais rápido e vença rivais em pistas cheias de obstáculos.',tags:['herói','corrida','poderes','plataforma','velocidade']},
  {id:'moon-city-stunt',cat:'corrida',badge:'hot',name:'Moon City Stunt',namePT:'Acrobacias na Lua',emoji:'🌙',rating:4.7,plays:1200000,year:2024,...gp('moon-city-stunt'),desc:'Realize acrobacias de carro numa cidade na Lua!',descLong:'Acrobacias na Lua oferece física diferenciada pela baixa gravidade. Faça saltos impossíveis e derrapes que desafiam as leis da física terrestre.',tags:['lua','acrobacia','carro','física','gravity']},
  {id:'flying-car',cat:'corrida',name:'Ultimate Flying Car',namePT:'Carro Voador',emoji:'🚀',rating:4.6,plays:980000,year:2024,...gp('ultimate-flying-car'),desc:'Dirija e voe com um carro futurista!',descLong:'Carro Voador é o simulador de veículo futurista mais completo. Seu carro pode dirigir em estradas ou decolar e voar em qualquer direção.',tags:['voador','carro','futurista','livre','simulador']},
  {id:'bloxd-io',cat:'corrida',badge:'top',name:'Bloxd.io',namePT:'Bloxd.io',emoji:'🟦',rating:4.8,plays:1650000,year:2024,...gp('bloxd-io'),desc:'Mundo blocado com corrida e aventura multiplayer!',descLong:'Bloxd.io é um mundo multiplayer de blocos com múltiplos modos incluindo corridas, labirintos e batalhas. Construa e compete com jogadores do mundo todo.',tags:['blocos','multiplayer','corrida','online','mundo']},
  {id:'body-drop',cat:'corrida',name:'Body Drop 3D',namePT:'Queda Épica 3D',emoji:'🎪',rating:4.6,plays:1100000,year:2024,...gp('body-drop-3d'),desc:'Deslize seu personagem pela rampa mais longa!',descLong:'Queda Épica 3D é um jogo único onde você empurra seu personagem pela maior rampa possível. Quanto mais longe ele chega, mais pontos você faz.',tags:['queda','rampa','3d','física','casual']},
  {id:'dino-merge-race',cat:'corrida',badge:'new',name:'Dino Merge Race',namePT:'Corrida de Dinos',emoji:'🦕',rating:4.5,plays:820000,year:2024,...gp('dino-merge-and-fight'),desc:'Combine dinossauros e entre em corridas épicas!',descLong:'Corrida de Dinos é um jogo híbrido de merge. Combine dinossauros para criar espécies mais rápidas e compita em corridas com suas criações evoluídas.',tags:['dinossauro','merge','corrida','evolução','híbrido']},

  // ══ PUZZLE (12) ══
  {id:'tentrix',cat:'puzzle',badge:'hot',featured:true,name:'Tentrix',namePT:'Tentrix',emoji:'🔷',rating:4.8,plays:1500000,year:2024,...gp('tentrix'),desc:'Encaixe peças e complete linhas nesse puzzle viciante!',descLong:'Tentrix é uma fusão genial do Tetris com puzzle de blocos. Arraste peças pentominó para o tabuleiro, complete linhas e ganhe pontos. Simples de aprender, impossível de parar.',tags:['puzzle','blocos','tetris','linhas','estratégia']},
  {id:'10x10',cat:'puzzle',badge:'top',name:'10x10',namePT:'10x10 Puzzle',emoji:'🟩',rating:4.7,plays:1250000,year:2024,...gp('10x10'),desc:'Encaixe blocos no grid 10x10 sem travar!',descLong:'10x10 Puzzle é um dos jogos de puzzle mais populares. Arraste peças de diferentes formatos para um grid, complete linhas para eliminá-las e jogue pelo maior tempo possível.',tags:['grid','blocos','linhas','puzzle','estratégia']},
  {id:'sort-balls',cat:'puzzle',badge:'new',name:'Sort Balls in Cones',namePT:'Ordena Bolinhas',emoji:'🧁',rating:4.7,plays:1100000,year:2024,...gp('sort-balls-cones'),desc:'Ordene as bolinhas por cor nos cones certos!',descLong:'Ordena Bolinhas é um puzzle de lógica colorido e relaxante. Mova bolinhas entre cones para agrupá-las por cor. Cada fase aumenta o número de cores tornando o desafio mais complexo.',tags:['cores','bolinhas','lógica','ordenar','relaxante']},
  {id:'kobadoo-flags',cat:'puzzle',name:'Kobadoo Flags',namePT:'Quiz de Bandeiras',emoji:'🚩',rating:4.5,plays:680000,year:2024,...gp('kobadoo-flags'),desc:'Adivinhe as bandeiras dos países do mundo!',descLong:'Quiz de Bandeiras é um jogo educativo e divertido. Identifique bandeiras de países ao redor do mundo e suba no ranking global de conhecimento geográfico.',tags:['bandeiras','países','quiz','geografia','educativo']},
  {id:'montezumba',cat:'puzzle',badge:'hot',name:'Montezumba',namePT:'Montezumba',emoji:'🐘',rating:4.6,plays:920000,year:2024,...gp('montezumba'),desc:'Conecte caminhos para o elefante passar!',descLong:'Montezumba é um puzzle de conexão relaxante. Rotacione e posicione peças para criar um caminho contínuo pelo qual o elefante possa passar. Centenas de níveis progressivos.',tags:['conexão','caminho','lógica','elefante','relaxante']},
  {id:'diamond-painting',cat:'puzzle',name:'Diamond Painting',namePT:'Pintura com Diamantes',emoji:'💎',rating:4.7,plays:1050000,year:2024,...gp('diamond-painting-by-number'),desc:'Preencha quadros com diamantes coloridos por número!',descLong:'Pintura com Diamantes é um jogo de arte pixel relaxante. Preencha cada célula do quadro com o diamante da cor correta para revelar imagens lindas.',tags:['diamante','pintura','pixel','relaxante','arte']},
  {id:'little-big-snake',cat:'puzzle',badge:'top',name:'Little Big Snake',namePT:'Cobrinhas.io',emoji:'🐍',rating:4.9,plays:2100000,year:2024,...gp('little-big-snake'),desc:'Coma, cresça e domine o mapa com sua cobra!',descLong:'Cobrinhas.io é o jogo multiplayer de cobras mais completo. Colete orbes para crescer, elimine cobras maiores e domine o ranking global. Com missões, upgrades e skins especiais.',tags:['cobra','io','multiplayer','crescer','online']},
  {id:'ships-3d',cat:'puzzle',name:'Ships 3D',namePT:'Batalha Naval 3D',emoji:'🚢',rating:4.6,plays:850000,year:2024,...gp('ships-3d'),desc:'Batalha naval em 3D contra a IA ou amigos!',descLong:'Batalha Naval 3D reinventa o clássico jogo de tabuleiro com gráficos tridimensionais. Posicione seus navios estrategicamente e afunde a frota adversária.',tags:['batalha naval','3d','tabuleiro','estratégia','navios']},
  {id:'dogeminer2',cat:'puzzle',badge:'new',name:'Dogeminer 2',namePT:'Doge Minerador 2',emoji:'🐕',rating:4.7,plays:980000,year:2024,...gp('dogeminer-2'),desc:'Mine Dogecoin e construa uma base na Lua!',descLong:'Doge Minerador 2 é um idle clicker com muito humor. Mine Dogecoin clicando, compre melhorias automáticas e construa uma base lunar incrível.',tags:['idle','clicker','doge','mineração','humor']},
  {id:'hoop-world',cat:'puzzle',name:'Hoop World',namePT:'Mundo dos Aros',emoji:'🏀',rating:4.5,plays:780000,year:2024,...gp('hoop-world'),desc:'Pule de aro em aro e chegue o mais longe possível!',descLong:'Mundo dos Aros é um jogo de habilidade simples e viciante. Toque para pular de aro em aro, acumule pontos e tente bater seu recorde.',tags:['aro','pulo','habilidade','recorde','casual']},
  {id:'ant-colony',cat:'puzzle',badge:'hot',name:'Ant Colony',namePT:'Colônia de Formigas',emoji:'🐜',rating:4.6,plays:890000,year:2024,...gp('ant-colony'),desc:'Construa e gerencie sua colônia de formigas!',descLong:'Colônia de Formigas é um simulador fascinante. Escave túneis, colete comida, proteja a rainha e expanda seu formigueiro. Observe a inteligência coletiva em ação.',tags:['formigas','colônia','simulador','construção','natureza']},
  {id:'what-the-hen',cat:'puzzle',badge:'new',name:'What the Hen',namePT:'Que Galinha!',emoji:'🐔',rating:4.5,plays:750000,year:2024,...gp('what-the-hen'),desc:'Bata no ovo, proteja a galinha e zere os inimigos!',descLong:'Que Galinha! é um jogo de defesa com mecânica única. Use sua galinha como arma para eliminar inimigos e proteger seus ovos. Física engraçada e gameplay estratégico.',tags:['galinha','defesa','ovos','física','humor']},

  // ══ ARCADE (12) ══
  {id:'cat-bricker',cat:'arcade',badge:'hot',featured:true,name:'Spinning Cat Bricker',namePT:'Gato Giratório',emoji:'🐱',rating:4.7,plays:1300000,year:2024,...gp('spinning-oia-oia-cat-bricker'),desc:'Gire o gato para quebrar tijolos e pontuar!',descLong:'Gato Giratório é um jogo arcade único e hilário. Faça seu gato girar na direção dos tijolos para quebrá-los todos. Combine o ângulo certo, use power-ups e marque pontos máximos.',tags:['gato','girar','tijolos','arcade','humor']},
  {id:'ragdoll-sandbox',cat:'arcade',badge:'top',name:'Ragdoll Sandbox',namePT:'Sandbox Ragdoll',emoji:'🤸',rating:4.8,plays:1550000,year:2024,...gp('last-play-ragdoll-sandbox'),desc:'Sandbox ragdoll caótico e infinitamente divertido!',descLong:'Sandbox Ragdoll é um playground de física caótica. Arremesse bonecos ragdoll, aplique forças, adicione objetos e observe a física hilária em ação. Modo criativo sem objetivos.',tags:['ragdoll','sandbox','física','caos','criativo']},
  {id:'gas-station-stickman',cat:'arcade',name:'Gas Station Stickman',namePT:'Posto de Gasolina Stickman',emoji:'⛽',rating:4.5,plays:870000,year:2024,...gp('gas-station-stick-simulator'),desc:'Gerencie o posto de gasolina mais movimentado!',descLong:'Posto de Gasolina Stickman é um simulador de gerenciamento frenético. Reabasteça carros, troque pneus e atenda clientes na velocidade máxima.',tags:['posto','gasolina','stickman','gerenciamento','correria']},
  {id:'basketball-stars',cat:'arcade',badge:'hot',name:'Basketball Stars',namePT:'Estrelas do Basquete',emoji:'🏀',rating:4.8,plays:1700000,year:2024,...gp('basketball-stars'),desc:'Basquete 1v1 ou 2v2 online multiplayer!',descLong:'Estrelas do Basquete é o melhor jogo de basquete de navegador. Jogue contra jogadores reais de todo o mundo. Customize seu atleta, aprenda movimentos especiais e suba no ranking.',tags:['basquete','multiplayer','1v1','online','esporte']},
  {id:'fortzone',cat:'arcade',badge:'new',name:'Fortzone Battle Royale',namePT:'Fortzone Battle Royale',emoji:'🎯',rating:4.7,plays:1250000,year:2024,...gp('fortzone-battle-royale'),desc:'Battle royale com construção no browser!',descLong:'Fortzone Battle Royale traz battle royale com construção para o navegador. Aterrisse, colete recursos, construa estruturas e elimine oponentes para ser o último sobrevivente.',tags:['battle royale','construção','sobrevivência','shooter','multiplayer']},
  {id:'shell-shockers',cat:'arcade',badge:'top',name:'Shell Shockers',namePT:'Shell Shockers',emoji:'🥚',rating:4.9,plays:2300000,year:2024,...gp('shell-shockers'),desc:'FPS multiplayer onde você é um ovo armado!',descLong:'Shell Shockers é um dos jogos multiplayer mais populares. Você controla um ovo armado em batalhas FPS frenéticas. Escolha sua classe e domine o ranking nesse shooter único.',tags:['ovo','fps','multiplayer','shooter','online']},
  {id:'survival-456',cat:'arcade',name:'Survival 456 Impostor',namePT:'Sobrevivente 456',emoji:'🦑',rating:4.7,plays:1400000,year:2024,...gp('survival-456-but-its-impostor'),desc:'Supere os jogos mortais e seja o impostor!',descLong:'Sobrevivente 456 mistura elementos de Squid Game com Among Us. Participe de jogos mortais, identifique o impostor e use estratégia para ser o último de pé.',tags:['squid game','impostor','sobrevivência','ação','among us']},
  {id:'funny-shooter2',cat:'arcade',badge:'new',name:'Funny Shooter 2',namePT:'Atirador Engraçado 2',emoji:'😂',rating:4.6,plays:980000,year:2024,...gp('funny-shooter-2'),desc:'Atire em bonecos bobos nesse shooter hilário!',descLong:'Atirador Engraçado 2 é um shooter repleto de humor. Elimine hordas de inimigos ridiculamente bobos com armas absurdas. Física ragdoll engraçada garante gargalhadas.',tags:['shooter','humor','ragdoll','ação','engraçado']},
  {id:'territorial-io',cat:'arcade',badge:'hot',name:'Territorial.io',namePT:'Territorial.io',emoji:'🗺️',rating:4.8,plays:1600000,year:2024,...gp('territorial-io'),desc:'Conquiste território e elimine todos os rivais!',descLong:'Territorial.io é um jogo de conquista de território multiplayer. Expanda sua área colorida, absorva inimigos menores e defenda-se dos maiores. O mapa tem espaço para apenas um vencedor.',tags:['território','conquista','io','multiplayer','estratégia']},
  {id:'strike-galaxy',cat:'arcade',badge:'top',name:'Strike Galaxy Attack',namePT:'Ataque à Galáxia',emoji:'👾',rating:4.8,plays:1450000,year:2024,...gp('strike-galaxy-attack'),desc:'Destrua frotas alienígenas em batalha espacial épica!',descLong:'Ataque à Galáxia é um shoot\'em up espacial vertical com gráficos deslumbrantes. Pilote sua nave, desvie de projéteis e destrua bosses massivos em batalhas épicas.',tags:['espaço','aliens','shootemup','nave','batalha']},
  {id:'bumpyball',cat:'arcade',name:'Bumpyball.io',namePT:'Bumpyball.io',emoji:'🏈',rating:4.5,plays:820000,year:2024,...gp('bumpyball-io'),desc:'Empurre a bola para fora da arena com sua bolha!',descLong:'Bumpyball.io é um jogo multijogador de física caótica. Controle uma bolha saltitante e empurre a bola para a área do adversário. Simples na teoria, incrivelmente divertido na prática.',tags:['bolha','bola','multiplayer','física','arena']},
  {id:'kopanito',cat:'arcade',name:'Kopanito All Stars Soccer',namePT:'Kopanito All Stars',emoji:'⚽',rating:4.7,plays:1100000,year:2024,...gp('kopanito-all-stars-soccer'),desc:'Futebol arcade rápido e frenético para todos!',descLong:'Kopanito All Stars é futebol estilo arcade anos 90. Sem faltas, sem regras chatas — apenas futebol veloz e divertido. Jogue sozinho ou com amigos em múltiplos modos.',tags:['futebol','arcade','multijogador','velocidade','retrô']},

  // ══ ESPORTE (12) ══
  {id:'penalty-kick-wiz',cat:'esporte',badge:'hot',featured:true,name:'Penalty Kick Wiz',namePT:'Mago do Pênalti',emoji:'⚽',rating:4.8,plays:1900000,year:2024,...gp('penalty-kick-wiz'),desc:'Marque e defenda pênaltis perfeitos!',descLong:'Mago do Pênalti é o melhor jogo de pênaltis da internet. Mire com precisão para marcar gols impossíveis e depois mude de lado para defender como goleiro acrobático.',tags:['pênalti','futebol','goleiro','precisão','copa']},
  {id:'penalty-shooters-2',cat:'esporte',badge:'top',name:'Penalty Shooters 2',namePT:'Disputa de Pênaltis 2',emoji:'🥅',rating:4.9,plays:2100000,year:2024,...gp('penalty-shooters-2'),desc:'Disputa de pênaltis com seleções do mundo todo!',descLong:'Disputa de Pênaltis 2 é o simulador de cobrança mais completo. Escolha sua seleção nacional e dispute torneios por fases com chutes precisos e defesas espetaculares.',tags:['pênalti','futebol','seleção','torneio','goleiro']},
  {id:'football-masters',cat:'esporte',badge:'hot',name:'Football Masters',namePT:'Mestres do Futebol',emoji:'🏆',rating:4.7,plays:1350000,year:2024,...gp('football-masters'),desc:'Futebol 1v1 rápido e viciante!',descLong:'Mestres do Futebol é futebol 1v1 de ação rápida. Escolha entre jogadores lendários, use habilidades especiais e marque gols espetaculares. Perfeito solo ou com amigo.',tags:['futebol','1v1','jogadores','lendas','competição']},
  {id:'football-heads',cat:'esporte',name:'Football Heads',namePT:'Cabeças de Futebol',emoji:'👤',rating:4.6,plays:1050000,year:2024,...gp('football-heads'),desc:'Futebol com cabeçadas e física maluca!',descLong:'Cabeças de Futebol é futebol arcade único. Personagens só de cabeça grande tentam marcar gols em partidas caóticas e divertidas com campeonatos de ligas europeias.',tags:['futebol','cabeça','arcade','ligas','engraçado']},
  {id:'foot-chinko-wc',cat:'esporte',badge:'new',name:'Foot Chinko World Cup',namePT:'Copa Foot Chinko',emoji:'🌎',rating:4.7,plays:1200000,year:2024,...gp('foot-chinko-world-cup'),desc:'Dispute a Copa do Mundo de futebol Chinko!',descLong:'Copa Foot Chinko é futebol estilo pinball. Deslize sua equipe para chutar a bola e marcar gols. Dispute o torneio da Copa do Mundo e leve seu país ao título.',tags:['futebol','copa do mundo','pinball','nações','torneio']},
  {id:'toon-cup',cat:'esporte',badge:'top',name:'Toon Cup',namePT:'Copa Cartoon',emoji:'🎨',rating:4.8,plays:1600000,year:2024,...gp('copa-toon'),desc:'Futebol com personagens de desenhos animados!',descLong:'Copa Cartoon é futebol com personagens animados. Escolha seu time favorito e dispute o torneio mais animado com física especial e habilidades únicas.',tags:['cartoon','futebol','personagens','torneio','crianças']},
  {id:'bball-stars-sport',cat:'esporte',badge:'hot',name:'Basketball Stars Sport',namePT:'Basketball Stars Esporte',emoji:'🏀',rating:4.8,plays:1700000,year:2024,...gp('basketball-stars'),desc:'O melhor jogo de basquete online grátis!',descLong:'Basketball Stars Esporte é basquete 1v1 mais competitivo. Enfrente jogadores reais de todo o mundo, customize seu atleta e suba no ranking global.',tags:['basquete','online','competitivo','ranking','esporte']},
  {id:'penalty-euro',cat:'esporte',name:'Penalty Shootout Euro',namePT:'Pênaltis Euro Cup',emoji:'🏅',rating:4.6,plays:950000,year:2024,...gp('penalty-shootout-euro-cup-2016'),desc:'Pênaltis da Eurocopa!',descLong:'Pênaltis Euro Cup simula a emoção das cobranças da Eurocopa. Escolha sua seleção europeia favorita e vença o nervoso duelo de pênaltis para ser campeão.',tags:['pênalti','eurocopa','europa','seleção','campeão']},
  {id:'boxing-stars',cat:'esporte',badge:'new',name:'Boxing Stars',namePT:'Estrelas do Boxe',emoji:'🥊',rating:4.7,plays:1100000,year:2024,...gp('boxing-stars'),desc:'Boxe multiplayer online com lutas em tempo real!',descLong:'Estrelas do Boxe é boxe online competitivo. Suba no ringue, enfrente adversários de todo o mundo em duelos em tempo real. Desvie, jabe e nocauteie para chegar ao topo.',tags:['boxe','multiplayer','ringue','competitivo','soco']},
  {id:'foot-chinko',cat:'esporte',name:'Foot Chinko',namePT:'Foot Chinko',emoji:'⚽',rating:4.5,plays:830000,year:2024,...gp('foot-chinko'),desc:'Futebol estilo pinball no campeonato mundial!',descLong:'Foot Chinko original com futebol estilo pinball adorado por milhões. Controle sua equipe deslizando pelo campo para chutar e marcar gols.',tags:['futebol','pinball','campeonato','diversão','habilidade']},
  {id:'soccer-managers',cat:'esporte',badge:'top',name:'Soccer Managers',namePT:'Gerentes de Futebol',emoji:'📊',rating:4.6,plays:880000,year:2024,...gp('top-10-soccer-managers'),desc:'Gerencie seu time de futebol e vença a liga!',descLong:'Gerentes de Futebol é um simulador de gerenciamento rápido. Escale jogadores, defina táticas, compre reforços e lidere seu time ao campeonato.',tags:['futebol','gerenciamento','tática','técnico','campeonato']},
  {id:'kopanito-sport',cat:'esporte',name:'Kopanito Sport',namePT:'Futebol Kopanito',emoji:'⚽',rating:4.7,plays:1050000,year:2024,...gp('kopanito-all-stars-soccer'),desc:'Futebol arcade rápido no modo esportivo!',descLong:'Futebol Kopanito Sport traz o futebol mais rápido e divertido. Dispute torneios com times de diferentes países em partidas curtas e frenéticas estilo anos 90.',tags:['futebol','esporte','arcade','torneio','times']},

  // ══ AVENTURA (12) ══
  {id:'battle-for-galaxy',cat:'aventura',badge:'hot',featured:true,name:'Battle for the Galaxy',namePT:'Batalha pela Galáxia',emoji:'🚀',rating:4.8,plays:1550000,year:2024,...gp('battle-for-the-galaxy'),desc:'Conquiste planetas e construa seu exército estelar!',descLong:'Batalha pela Galáxia é um MMO estratégico de ficção científica. Construa bases em planetas, forme alianças e dispute o controle da galáxia com milhares de jogadores.',tags:['galáxia','estratégia','mmo','conquista','ficção científica']},
  {id:'robot-terminator',cat:'aventura',badge:'top',name:'Robot T-Rex',namePT:'Robô Exterminador',emoji:'🤖',rating:4.7,plays:1200000,year:2024,...gp('robot-terminator-t-rex'),desc:'Controle um robô T-Rex e destrua tudo!',descLong:'Robô Exterminador coloca você no controle de um T-Rex mecânico colossal. Destrua edifícios, tanques e helicópteros enquanto atravessa cidades em missões progressivas.',tags:['robô','t-rex','destruição','mecha','ação']},
  {id:'stickman-hero',cat:'aventura',name:'Stickman Hero Fight',namePT:'Stickman Herói',emoji:'🥷',rating:4.6,plays:960000,year:2024,...gp('stickman-hero-fight'),desc:'Seja o herói stickman que salva o mundo!',descLong:'Stickman Herói é ação-aventura com missões épicas. Atravesse mundos perigosos, derrote chefes poderosos e salve cidadãos com golpes fluidos.',tags:['stickman','herói','aventura','missões','ação']},
  {id:'territorial-adventure',cat:'aventura',badge:'hot',name:'Territorial Conquest',namePT:'Conquista Territorial',emoji:'🗺️',rating:4.8,plays:1550000,year:2024,...gp('territorial-io'),desc:'Expanda seu território e domine o mapa!',descLong:'Conquista Territorial é aventura de exploração e domínio. Expanda sua área de controle, absorva territórios rivais e use estratégia para ser o jogador com maior influência.',tags:['território','conquista','io','mapa','exploração']},
  {id:'narrow-adventure',cat:'aventura',name:'Narrow Castle Quest',namePT:'Defesa do Castelo',emoji:'🏰',rating:4.7,plays:1250000,year:2024,...gp('narrow-one'),desc:'Defenda seu castelo com arco e flecha medieval!',descLong:'Defesa do Castelo é uma aventura medieval de captura de bandeira. Use seu arco com precisão para eliminar invasores, defender seu castelo e capturar a bandeira inimiga.',tags:['medieval','arco','castelo','aventura','defesa']},
  {id:'ant-world',cat:'aventura',badge:'new',name:'Ant World',namePT:'Mundo das Formigas',emoji:'🌿',rating:4.6,plays:880000,year:2024,...gp('ant-colony'),desc:'Expanda seu formigueiro numa aventura subterrânea!',descLong:'Mundo das Formigas é uma aventura de simulação única. Escave túneis, explore novos territórios e proteja sua rainha de aranhas e predadores.',tags:['formigas','subterrâneo','exploração','natureza','simulador']},
  {id:'doge-adventure',cat:'aventura',badge:'top',name:'Doge to the Moon',namePT:'Doge para a Lua',emoji:'🌙',rating:4.7,plays:1050000,year:2024,...gp('dogeminer-2'),desc:'Mine Doge e construa sua base lunar!',descLong:'Doge para a Lua é uma aventura de mineração e exploração espacial. Construa foguetes, explore asteroides e mine quantidades inimagináveis de Dogecoin.',tags:['doge','lua','mineração','exploração','espaço']},
  {id:'superhero-city',cat:'aventura',name:'Superhero City',namePT:'Cidade dos Super-Heróis',emoji:'🦸',rating:4.6,plays:950000,year:2024,...gp('the-superhero-league'),desc:'Salve a cidade dos vilões com seus superpoderes!',descLong:'Cidade dos Super-Heróis é aventura urbana de ação. Voe pela cidade, enfrente vilões em missões variadas e salve cidadãos em perigo usando superpoderes únicos.',tags:['herói','cidade','aventura','poderes','missões']},
  {id:'archery-quest',cat:'aventura',name:'Archery Quest',namePT:'Missão do Arqueiro',emoji:'🎯',rating:4.5,plays:790000,year:2024,...gp('stickman-archero-fight'),desc:'Complete missões épicas com seu arco!',descLong:'Missão do Arqueiro é uma aventura roguelite viciante. Explore masmorras geradas aleatoriamente, colete power-ups únicos e evolua seu arqueiro para enfrentar inimigos mais poderosos.',tags:['arqueiro','missão','roguelite','aventura','evolução']},
  {id:'merge-warriors',cat:'aventura',badge:'hot',name:'Merge Warriors',namePT:'Guerreiros Merge',emoji:'⚔️',rating:4.7,plays:1050000,year:2024,...gp('merge-battle-tactics'),desc:'Combine guerreiros e explore mundos de fantasia!',descLong:'Guerreiros Merge mistura idle merge com exploração de mundos. Combine guerreiros para criar heróis poderosos e explore novos mapas em mundos de fantasia.',tags:['merge','guerreiros','aventura','fantasia','exploração']},
  {id:'gladiator-quest',cat:'aventura',badge:'new',name:'Gladiator Quest',namePT:'Missão do Gladiador',emoji:'🏛️',rating:4.6,plays:890000,year:2024,...gp('gladiators-merge-and-fight'),desc:'Lute no Coliseu e torne-se lenda romana!',descLong:'Missão do Gladiador é aventura histórica no Império Romano. Lute no Coliseu, ganhe a multidão e suba de escravo a lenda para conquistar sua liberdade.',tags:['gladiador','coliseu','roma','histórico','aventura']},
  {id:'bloxd-adventure',cat:'aventura',badge:'hot',name:'Bloxd Adventure',namePT:'Aventura Bloxd',emoji:'🟦',rating:4.8,plays:1650000,year:2024,...gp('bloxd-io'),desc:'Explore mundos de blocos em aventura multiplayer!',descLong:'Aventura Bloxd é um sandbox de blocos com múltiplos modos de jogo. Explore mundos procedurais, construa estruturas e viva aventuras multiplayer emocionantes.',tags:['blocos','aventura','sandbox','multiplayer','exploração']},

  // ══ TIRO (12) ══
  {id:'shell-shockers-tiro',cat:'tiro',badge:'top',featured:true,name:'Shell Shockers FPS',namePT:'Shell Shockers FPS',emoji:'🥚',rating:4.9,plays:2300000,year:2024,...gp('shell-shockers'),desc:'FPS multiplayer onde ovos guerreiam entre si!',descLong:'Shell Shockers FPS é um dos jogos de tiro multiplayer mais únicos. Você é um ovo com armas. Elimine inimigos em mapas variados e desbloqueie equipamentos épicos.',tags:['fps','ovo','tiro','multiplayer','online']},
  {id:'funny-shooter-tiro',cat:'tiro',badge:'hot',name:'Funny Shooter Arena',namePT:'Atirador Engraçado',emoji:'🎪',rating:4.7,plays:1400000,year:2024,...gp('funny-shooter-2'),desc:'Elimine inimigos hilários nessa arena de tiro!',descLong:'Atirador Engraçado é shooter de hordas repleto de humor. Enfrente inimigos absurdos com armas ridículas. Desbloqueie upgrades malucos e sobreviva o máximo.',tags:['tiro','humor','horda','arena','engraçado']},
  {id:'fortzone-tiro',cat:'tiro',badge:'new',name:'Fortzone Shooter',namePT:'Fortzone Tiro',emoji:'🔫',rating:4.7,plays:1250000,year:2024,...gp('fortzone-battle-royale'),desc:'Battle royale de tiro com construção!',descLong:'Fortzone Shooter é o battle royale com construção mais divertido do navegador. Colete materiais, construa coberturas e use sua pontaria para eliminar adversários.',tags:['battle royale','tiro','construção','shooter','sobrevivência']},
  {id:'galaxy-strike-tiro',cat:'tiro',badge:'top',name:'Galaxy Strike Force',namePT:'Força Galáctica',emoji:'🚀',rating:4.8,plays:1450000,year:2024,...gp('strike-galaxy-attack'),desc:'Pilote sua nave e destrua frotas alienígenas!',descLong:'Força Galáctica é um shoot\'em up vertical clássico com visual moderno. Desvie de projéteis e destrua bosses massivos em batalhas épicas pelo espaço.',tags:['nave','shootemup','galáxia','aliens','tiro']},
  {id:'survival-tiro',cat:'tiro',name:'Survival Shooter',namePT:'Atirador Sobrevivente',emoji:'🦑',rating:4.6,plays:1200000,year:2024,...gp('survival-456-but-its-impostor'),desc:'Sobreviva atirando nos impostores!',descLong:'Atirador Sobrevivente mistura jogos mortais com tiro. Identifique impostores e elimine-os antes de ser eliminado. Reflexos e estratégia são essenciais.',tags:['sobrevivência','tiro','impostor','ação','suspense']},
  {id:'narrow-archer-tiro',cat:'tiro',badge:'hot',name:'Narrow One Archer',namePT:'Arqueiro Narrow One',emoji:'🏹',rating:4.8,plays:1380000,year:2024,...gp('narrow-one'),desc:'Tiro com arco multiplayer de captura de bandeira!',descLong:'Arqueiro Narrow One é shooter medieval multiplayer de captura de bandeira. Use sua mira para eliminar adversários em partidas curtas e intensas.',tags:['arco','tiro','medieval','captura','multiplayer']},
  {id:'stickman-shooter',cat:'tiro',name:'Stickman Shooter',namePT:'Stickman Atirador',emoji:'🎯',rating:4.6,plays:950000,year:2024,...gp('stickman-archero-fight'),desc:'Atire com precisão e elimine todos os stickmen!',descLong:'Stickman Atirador é roguelite de tiro viciante. Atire automaticamente em inimigos enquanto se move pelo mapa. Colete power-ups que amplificam seus tiros.',tags:['stickman','tiro','roguelite','automático','horda']},
  {id:'brutal-shooter',cat:'tiro',badge:'hot',name:'Brutal Shooter',namePT:'Atirador Brutal',emoji:'💥',rating:4.7,plays:1050000,year:2024,...gp('brutal-defender'),desc:'Defenda sua posição com tiros brutais!',descLong:'Atirador Brutal é shooter de sobrevivência intenso. Fique atrás de sua barricada, atire em ondas de inimigos e use explosivos para manter sua posição o máximo possível.',tags:['shooter','sobrevivência','defesa','ondas','brutal']},
  {id:'merge-shooter',cat:'tiro',badge:'new',name:'Merge & Shoot',namePT:'Merge e Atira',emoji:'🔮',rating:4.6,plays:890000,year:2024,...gp('merge-battle-tactics'),desc:'Combine armas e atire em tudo que aparecer!',descLong:'Merge e Atira combina idle merge com shooter de hordas. Combine diferentes armas para criar canhões mais poderosos e elimine ondas crescentes de inimigos.',tags:['merge','tiro','armas','horda','shooter']},
  {id:'gang-shooter',cat:'tiro',name:'Gang City Shooter',namePT:'Atirador da Cidade',emoji:'🔫',rating:4.5,plays:820000,year:2024,...gp('city-of-gang-street-fighting'),desc:'Limpe as ruas da cidade com tiros precisos!',descLong:'Atirador da Cidade é tiro urbano clássico. Percorra bairros perigosos, use coberturas e elimine gangues que infestam a cidade com diferentes armas desbloqueáveis.',tags:['tiro','cidade','gangue','cobertura','urbano']},
  {id:'superhero-shooter',cat:'tiro',badge:'top',name:'Superhero Shooter',namePT:'Atirador Super-Herói',emoji:'🦸',rating:4.7,plays:1050000,year:2024,...gp('superhero-race'),desc:'Use superpoderes para eliminar vilões!',descLong:'Atirador Super-Herói é shooter com poderes especiais. Jogue como herói e use laser, trovão e raios de gelo para eliminar vilões em missões épicas.',tags:['herói','poderes','shooter','vilão','missões']},
  {id:'territorial-shooter',cat:'tiro',badge:'new',name:'Territory Shooter',namePT:'Atirador Territorial',emoji:'🗺️',rating:4.7,plays:1100000,year:2024,...gp('territorial-io'),desc:'Conquiste território eliminando inimigos com tiros!',descLong:'Atirador Territorial combina conquista de território com ação de tiro. Elimine adversários para expandir sua zona de controle e domine o mapa inteiro.',tags:['território','tiro','conquista','ação','io']},

  // ══ ESTRATÉGIA (12) ══
  {id:'territorial-strategy',cat:'estrategia',badge:'top',featured:true,name:'Territorial Strategy',namePT:'Estratégia Territorial',emoji:'♟️',rating:4.8,plays:1600000,year:2024,...gp('territorial-io'),desc:'Conquiste o maior território e domine o mapa!',descLong:'Estratégia Territorial é o jogo de conquista multiplayer mais viciante. Expanda sua área, absorva rivais menores e use táticas para defender fronteiras.',tags:['território','estratégia','conquista','mapa','multiplayer']},
  {id:'galaxy-empire',cat:'estrategia',badge:'hot',name:'Galaxy Empire',namePT:'Império Galáctico',emoji:'🌌',rating:4.8,plays:1500000,year:2024,...gp('battle-for-the-galaxy'),desc:'Construa um império espacial e conquiste galáxias!',descLong:'Império Galáctico é estratégia 4X épica. Construa frotas espaciais, colonize planetas, negocie com aliados e declare guerras para expandir seu domínio pela galáxia.',tags:['galáxia','4x','império','estratégia','conquista']},
  {id:'naval-strategy',cat:'estrategia',badge:'new',name:'Naval Strategy',namePT:'Estratégia Naval',emoji:'⚓',rating:4.7,plays:1100000,year:2024,...gp('ships-3d'),desc:'Monte sua frota e domine os oceanos!',descLong:'Estratégia Naval é batalha naval com profundidade estratégica real. Posicione sua frota, preveja os movimentos adversários e afunde todos os navios inimigos.',tags:['naval','estratégia','navios','batalha','tático']},
  {id:'merge-strategy',cat:'estrategia',badge:'top',name:'Merge Strategy',namePT:'Merge Estratégia',emoji:'🔮',rating:4.7,plays:1050000,year:2024,...gp('merge-battle-tactics'),desc:'Combine unidades e desenvolva a melhor estratégia!',descLong:'Merge Estratégia é fusão perfeita de idle merge com estratégia por turnos. Combine tropas, desenvolva tecnologias e conquiste mapas com crescente dificuldade.',tags:['merge','estratégia','tropas','turn-based','conquista']},
  {id:'gladiator-empire',cat:'estrategia',name:'Gladiator Empire',namePT:'Império dos Gladiadores',emoji:'🏛️',rating:4.6,plays:900000,year:2024,...gp('gladiators-merge-and-fight'),desc:'Gerencie gladiadores e conquiste o Coliseu!',descLong:'Império dos Gladiadores é gerenciador de arena romano. Recrute gladiadores, treine-os e construa o maior espetáculo de Roma com combates épicos.',tags:['gladiador','gerenciamento','roma','estratégia','arena']},
  {id:'stickman-army',cat:'estrategia',badge:'hot',name:'Stickman Army',namePT:'Exército Stickman',emoji:'⚔️',rating:4.7,plays:1150000,year:2024,...gp('stickman-fighter-mega-brawl'),desc:'Comande um exército de stickmen em batalhas épicas!',descLong:'Exército Stickman é RTS simplificado e viciante. Produza unidades stickman, envie-as para atacar e defenda sua base. Gerencie recursos e produza unidades especializadas.',tags:['stickman','exército','rts','batalha','estratégia']},
  {id:'ant-conquest',cat:'estrategia',badge:'new',name:'Ant Conquest',namePT:'Conquista das Formigas',emoji:'🐜',rating:4.6,plays:880000,year:2024,...gp('ant-colony'),desc:'Expanda sua colônia e domine outras rainhas!',descLong:'Conquista das Formigas é estratégia de colônia profundo. Envie soldados para conquistar colônias rivais e dominar o território subterrâneo.',tags:['formigas','estratégia','colônia','conquista','recursos']},
  {id:'fortress-defense',cat:'estrategia',name:'Fortress Defense',namePT:'Defesa da Fortaleza',emoji:'🏰',rating:4.6,plays:950000,year:2024,...gp('narrow-one'),desc:'Defenda sua fortaleza medieval com estratégia!',descLong:'Defesa da Fortaleza é defesa estratégica medieval. Posicione arqueiros, catapultas e armadilhas para repelir ondas de invasores cada vez mais intensas.',tags:['fortaleza','defesa','medieval','estratégia','arqueiro']},
  {id:'crypto-empire',cat:'estrategia',badge:'top',name:'Crypto Empire',namePT:'Império Cripto',emoji:'💰',rating:4.7,plays:1000000,year:2024,...gp('dogeminer-2'),desc:'Construa seu império de mineração de cripto!',descLong:'Império Cripto é idle game de estratégia econômica. Comece minerando manualmente, automatize com trabalhadores e construa o maior império de mineração da galáxia.',tags:['cripto','mineração','idle','estratégia','econômico']},
  {id:'mech-strategy',cat:'estrategia',name:'Mech War Strategy',namePT:'Estratégia Mech',emoji:'🤖',rating:4.6,plays:920000,year:2024,...gp('robot-terminator-t-rex'),desc:'Controle mechs e conquiste o campo de batalha!',descLong:'Estratégia Mech é estratégia por turnos com robôs gigantes. Posicione seus mechs, use habilidades especiais de cada modelo e domine o adversário com táticas superiores.',tags:['mech','robô','estratégia','turnos','batalha']},
  {id:'bloxd-strategy',cat:'estrategia',badge:'hot',name:'Bloxd Conquer',namePT:'Bloxd Conquista',emoji:'🟦',rating:4.8,plays:1650000,year:2024,...gp('bloxd-io'),desc:'Construa bases e conquiste territórios em blocos!',descLong:'Bloxd Conquista é sandbox de blocos com estratégia. Construa fortalezas elaboradas, defenda seu território e expanda seu reino digital contra outros jogadores.',tags:['blocos','construção','conquista','sandbox','multiplayer']},
  {id:'hero-league-wars',cat:'estrategia',badge:'new',name:'Hero League Wars',namePT:'Guerras dos Heróis',emoji:'🦸',rating:4.7,plays:1050000,year:2024,...gp('the-superhero-league'),desc:'Forme seu time de heróis e domine a liga!',descLong:'Guerras dos Heróis é autobattler estratégico. Recrute heróis com habilidades únicas, posicione-os antes das batalhas e veja-os lutar. Quem escolhe melhor vence.',tags:['heróis','liga','autobattler','estratégia','equipe']},

  // ══ MENINAS (12) ══
  {id:'diamond-art-meninas',cat:'meninas',badge:'hot',featured:true,name:'Diamond Painting Art',namePT:'Arte de Diamantes',emoji:'💎',rating:4.8,plays:1450000,year:2024,...gp('diamond-painting-by-number'),desc:'Crie obras de arte preenchendo com diamantes coloridos!',descLong:'Arte de Diamantes é o jogo de arte pixel mais relaxante. Preencha cada célula com o diamante da cor correta para revelar imagens deslumbrantes de paisagens e personagens.',tags:['diamante','arte','pixel','relaxante','criativo']},
  {id:'sort-balls-meninas',cat:'meninas',badge:'top',name:'Color Balls Spa',namePT:'Spa Colorido',emoji:'🎀',rating:4.7,plays:1100000,year:2024,...gp('sort-balls-cones'),desc:'Organize bolinhas coloridas em cones temáticos de spa!',descLong:'Spa Colorido é puzzle de organização com tema de beleza. Ordene bolinhas por cor nos cones corretos em ambientes inspirados em spas luxuosos. Relaxante e desafiador.',tags:['spa','cores','puzzle','relaxante','beleza']},
  {id:'flags-meninas',cat:'meninas',badge:'new',name:'Flag Fashion Quiz',namePT:'Moda e Bandeiras',emoji:'🌍',rating:4.5,plays:680000,year:2024,...gp('kobadoo-flags'),desc:'Aprenda sobre países e suas culturas de moda!',descLong:'Moda e Bandeiras combina moda e geografia. Identifique bandeiras de países, descubra curiosidades sobre suas culturas e estilos. Ganhe pontos e desbloqueie looks inspirados em cada nação.',tags:['bandeiras','moda','quiz','culturas','países']},
  {id:'basketball-girls',cat:'meninas',name:'Basketball Girls',namePT:'Basquete Feminino',emoji:'🏀',rating:4.6,plays:870000,year:2024,...gp('basketball-stars'),desc:'Jogue basquete com atletas femininas incríveis!',descLong:'Basquete Feminino é versão do popular Basketball Stars com atletas femininas. Desafie oponentes em 1v1 intensos, customize sua jogadora e suba no ranking.',tags:['basquete','feminino','esporte','online','competição']},
  {id:'hoop-girl',cat:'meninas',badge:'hot',name:'Hoop Girl',namePT:'Garota dos Aros',emoji:'🌈',rating:4.7,plays:1050000,year:2024,...gp('hoop-world'),desc:'Pule de aro em aro com sua personagem fofa!',descLong:'Garota dos Aros é versão adorável do Hoop World. Controle uma personagem fofa e pule de aro em aro com timing perfeito. Colete estrelas e bata seu recorde.',tags:['aro','pulo','fofo','personagem','recorde']},
  {id:'elephant-garden',cat:'meninas',badge:'new',name:'Elephant Garden',namePT:'Jardim do Elefante',emoji:'🌺',rating:4.6,plays:890000,year:2024,...gp('montezumba'),desc:'Ajude o elefantinho a encontrar seu caminho florido!',descLong:'Jardim do Elefante é puzzle de caminho adorável. Rotacione peças para criar um caminho florido pelo qual o elefantinho possa passar com segurança. Cenários coloridos e encantadores.',tags:['elefante','jardim','puzzle','flores','fofo']},
  {id:'happy-hen',cat:'meninas',name:'Happy Hen Farm',namePT:'Fazenda da Galinha',emoji:'🐓',rating:4.5,plays:760000,year:2024,...gp('what-the-hen'),desc:'Cuide da galinha e colete ovos na fazenda!',descLong:'Fazenda da Galinha é jogo de fazenda com a galinha mais engraçada. Alimente as galinhas, colete ovos, proteja-as de predadores e expanda sua fazenda.',tags:['fazenda','galinha','ovos','cuidado','fofo']},
  {id:'doge-treasure',cat:'meninas',badge:'hot',name:'Doge Treasure Hunt',namePT:'Caça ao Tesouro Doge',emoji:'🐶',rating:4.6,plays:980000,year:2024,...gp('dogeminer-2'),desc:'Ajude o cachorrinho Doge a encontrar tesouros!',descLong:'Caça ao Tesouro Doge é aventura de mineração com o adorável Doge. Cave buracos, encontre moedas brilhantes e desbloqueie recompensas para decorar a casinha do Doge.',tags:['doge','cachorro','tesouro','fofo','idle']},
  {id:'superhero-girls',cat:'meninas',badge:'top',name:'Superhero Girls Race',namePT:'Super-Heroínas',emoji:'🦸‍♀️',rating:4.7,plays:1100000,year:2024,...gp('superhero-race'),desc:'Corra com as super-heroínas mais incríveis!',descLong:'Super-Heroínas é corrida de plataforma com personagens femininas poderosas. Escolha sua heroína favorita, use superpoderes para se mover mais rápido e vença rivais.',tags:['heroína','corrida','poderes','feminino','ação']},
  {id:'ant-garden',cat:'meninas',name:'Ant Garden Girls',namePT:'Jardim das Formigas',emoji:'🌸',rating:4.5,plays:730000,year:2024,...gp('ant-colony'),desc:'Cuide do jardim e das formigas trabalhadoras!',descLong:'Jardim das Formigas é versão fofa do Ant Colony. Construa um jardim encantado, cuide das suas formigas trabalhadoras e crie o formigueiro mais bonito.',tags:['jardim','formigas','natureza','fofo','cuidado']},
  {id:'dance-drop',cat:'meninas',badge:'new',name:'Dance Drop',namePT:'Dance Drop',emoji:'💃',rating:4.5,plays:810000,year:2024,...gp('body-drop-3d'),desc:'Deslize e dance pela rampa em ritmo colorido!',descLong:'Dance Drop é versão musical do Body Drop 3D. Deslize seu personagem dançarino pela rampa, colete notas musicais e complete coreografias especiais para pontuar.',tags:['dança','música','colorido','rampa','ritmo']},
  {id:'stickwoman',cat:'meninas',name:'Stickwoman Quest',namePT:'Aventura Stickwoman',emoji:'👧',rating:4.5,plays:790000,year:2024,...gp('stickman-hero-fight'),desc:'A stickwoman mais corajosa em sua aventura épica!',descLong:'Aventura Stickwoman coloca você no controle de uma heroína stickman determinada. Enfrente inimigos em missões progressivas, colete power-ups e salve o mundo.',tags:['stickwoman','aventura','heroína','missões','ação']},

  // ══ CASUAL (10) ══
  {id:'tentrix-casual',cat:'casual',badge:'hot',featured:true,name:'Tentrix Relax',namePT:'Tentrix Relax',emoji:'🔷',rating:4.8,plays:1500000,year:2024,...gp('tentrix'),desc:'Puzzle de blocos relaxante para jogar no seu tempo!',descLong:'Tentrix Relax é a experiência de puzzle mais tranquila. Sem timer, sem pressão — apenas arraste peças e complete linhas no seu ritmo.',tags:['puzzle','relaxante','blocos','casual','tranquilo']},
  {id:'10x10-casual',cat:'casual',badge:'top',name:'10x10 Casual',namePT:'10x10 Casual',emoji:'🟩',rating:4.7,plays:1250000,year:2024,...gp('10x10'),desc:'O clássico 10x10 para jogar quando quiser!',descLong:'10x10 Casual é o puzzle de grid mais popular para momentos de pausa. Encaixe peças e acumule a maior pontuação sem pressa.',tags:['grid','casual','blocos','puzzle','pontuação']},
  {id:'doge-clicker',cat:'casual',badge:'new',name:'Idle Doge Clicker',namePT:'Clicker do Doge',emoji:'🐕',rating:4.6,plays:980000,year:2024,...gp('dogeminer-2'),desc:'Clique, mine e acumule Doge sem parar!',descLong:'Clicker do Doge é idle game casual viciante. Clique para minerar Doge, compre melhorias automáticas e veja seus lucros crescerem exponencialmente.',tags:['idle','clicker','doge','casual','viciante']},
  {id:'little-snake-casual',cat:'casual',badge:'hot',name:'Little Snake Fun',namePT:'Cobrinhas',emoji:'🐍',rating:4.9,plays:2100000,year:2024,...gp('little-big-snake'),desc:'Cobrinhas multiplayer casual para jogar qualquer hora!',descLong:'Cobrinhas é a versão mais acessível do Little Big Snake. Partidas curtas e intensas perfeitas para qualquer momento do dia.',tags:['cobra','casual','multiplayer','io','diversão']},
  {id:'hoop-casual',cat:'casual',name:'Hoop Jump Casual',namePT:'Pulo no Aro',emoji:'🏅',rating:4.5,plays:780000,year:2024,...gp('hoop-world'),desc:'Pule de aro em aro no ritmo casual perfeito!',descLong:'Pulo no Aro é experiência de pulos mais tranquila. Salte de aro em aro com timing simples e acumule pontos progressivamente.',tags:['aro','pulo','casual','ritmo','recorde']},
  {id:'diamonds-relax',cat:'casual',badge:'top',name:'Diamond Art Relax',namePT:'Arte Diamante',emoji:'💎',rating:4.7,plays:1050000,year:2024,...gp('diamond-painting-by-number'),desc:'Pintura com diamantes para momentos de relaxamento!',descLong:'Arte Diamante é atividade ideal para desestressar. Preencha padrões coloridos com diamantes virtuais e veja lindas imagens tomarem forma.',tags:['diamante','arte','relaxante','casual','pixel']},
  {id:'elephant-casual',cat:'casual',name:'Elephant Path',namePT:'Caminho do Elefante',emoji:'🐘',rating:4.5,plays:750000,year:2024,...gp('montezumba'),desc:'Guie o elefante pelo caminho no ritmo casual!',descLong:'Caminho do Elefante é puzzle de rotação de peças sem pressão. Gire e posicione peças para criar o caminho ideal. Centenas de níveis progressivos.',tags:['elefante','puzzle','casual','rotação','relaxante']},
  {id:'ant-idle',cat:'casual',badge:'hot',name:'Ant Farm Idle',namePT:'Fazenda de Formigas',emoji:'🐜',rating:4.6,plays:890000,year:2024,...gp('ant-colony'),desc:'Monte sua fazenda de formigas no ritmo casual!',descLong:'Fazenda de Formigas Casual é simulador idle de formigueiro. Deixe as formigas trabalharem automaticamente e expanda o formigueiro no seu ritmo.',tags:['formigas','idle','casual','fazenda','relaxante']},
  {id:'kopanito-fun',cat:'casual',name:'Kopanito Fun',namePT:'Futebol Casual',emoji:'⚽',rating:4.7,plays:1100000,year:2024,...gp('kopanito-all-stars-soccer'),desc:'Futebol arcade divertido no modo casual!',descLong:'Futebol Casual Kopanito é futebol mais descompromissado. Jogue partidas rápidas sem pressão de campeonato com física maluca e personagens caricatos.',tags:['futebol','casual','arcade','diversão','rápido']},
  {id:'bumpyball-casual',cat:'casual',badge:'new',name:'Bumpy Ball Fun',namePT:'Bola Saltitante',emoji:'⚽',rating:4.6,plays:820000,year:2024,...gp('bumpyball-io'),desc:'Bola saltitante em modo casual divertido!',descLong:'Bola Saltitante traz a física maluca do Bumpyball para modo relaxado. Controle sua bolha e empurre a bola em partidas descompromissadas.',tags:['bolha','bola','casual','física','diversão']},

  // ══ 2 JOGADORES (10) ══
  {id:'basketball-2p',cat:'2jogadores',badge:'hot',featured:true,name:'Basketball Stars 2P',namePT:'Basquete 2 Jogadores',emoji:'🏀',rating:4.9,plays:1800000,year:2024,...gp('basketball-stars'),desc:'Basquete 1v1 com seu amigo no mesmo PC!',descLong:'Basquete 2 Jogadores é a disputa mais emocionante para duplas. Use o teclado compartilhado para driblar, arremessar e vencer a partida.',tags:['basquete','2 jogadores','1v1','amigo','competição']},
  {id:'football-2p',cat:'2jogadores',badge:'top',name:'Football Masters 2P',namePT:'Futebol 2 Jogadores',emoji:'⚽',rating:4.9,plays:1900000,year:2024,...gp('football-masters'),desc:'Futebol 1v1 épico para dois jogadores!',descLong:'Futebol 2 Jogadores é a disputa mais épica para dois amigos. Escolha jogadores lendários, use habilidades especiais e marque gols espetaculares.',tags:['futebol','2 jogadores','1v1','lendas','amigo']},
  {id:'boxing-2p',cat:'2jogadores',badge:'new',name:'Boxing Stars 2P',namePT:'Boxe 2 Jogadores',emoji:'🥊',rating:4.8,plays:1200000,year:2024,...gp('boxing-stars'),desc:'Enfrente seu amigo no ringue de boxe!',descLong:'Boxe 2 Jogadores coloca dois lutadores frente a frente com controles divididos. Golpeie, esquive e nocauteie seu oponente antes que ele faça o mesmo.',tags:['boxe','2 jogadores','ringue','nocaute','amigo']},
  {id:'penalty-2p',cat:'2jogadores',badge:'hot',name:'Penalty Duel 2P',namePT:'Pênaltis 2 Jogadores',emoji:'🥅',rating:4.8,plays:1450000,year:2024,...gp('penalty-kick-wiz'),desc:'Disputa de pênaltis épica com seu amigo!',descLong:'Pênaltis 2 Jogadores é a disputa mais emocionante. Um chuta, o outro defende! Alterne e descubra quem tem o maior sangue frio sob pressão.',tags:['pênalti','2 jogadores','futebol','goleiro','nervos']},
  {id:'kopanito-2p',cat:'2jogadores',name:'Kopanito 2 Players',namePT:'Kopanito 2P',emoji:'⚽',rating:4.7,plays:1100000,year:2024,...gp('kopanito-all-stars-soccer'),desc:'Futebol arcade frenético para dois amigos!',descLong:'Kopanito 2P é futebol arcade estilo anos 90 para duplas. Controle seus times com metades do teclado em partidas rápidas e épicas.',tags:['futebol','2 jogadores','arcade','frenético','amigo']},
  {id:'narrow-2p',cat:'2jogadores',badge:'top',name:'Narrow One 2P',namePT:'Narrow One 2P',emoji:'🏹',rating:4.8,plays:1380000,year:2024,...gp('narrow-one'),desc:'Captura de bandeira com arcos para dois jogadores!',descLong:'Narrow One 2P transforma o shooter medieval em batalha local. Divida o teclado, controle seus arqueiros e dispute captura de bandeira.',tags:['arco','2 jogadores','captura','medieval','estratégia']},
  {id:'bumpyball-2p',cat:'2jogadores',badge:'new',name:'Bumpyball Duel',namePT:'Duelo Bumpyball',emoji:'🏈',rating:4.7,plays:1050000,year:2024,...gp('bumpyball-io'),desc:'Duelo de bolhas saltitantes para dois jogadores!',descLong:'Bumpyball Duelo é física caótica para dois. Controle bolhas com metades do teclado e empurre a bola para o gol adversário.',tags:['bolha','2 jogadores','duelo','física','diversão']},
  {id:'slope-2p',cat:'2jogadores',badge:'hot',name:'Slope Race 2P',namePT:'Slope 2 Jogadores',emoji:'⛷️',rating:4.8,plays:1600000,year:2024,...gp('slope-racing-3d'),desc:'Corrida em rampa 3D entre dois jogadores!',descLong:'Slope 2P é a competição de reflexos mais emocionante para dois. Ambos descem a mesma rampa vertiginosa ao mesmo tempo. O primeiro a cair perde.',tags:['slope','2 jogadores','corrida','reflexo','3d']},
  {id:'crash-derby-2p',cat:'2jogadores',name:'Crash Derby 2P',namePT:'Derby de Colisão 2P',emoji:'💥',rating:4.7,plays:1050000,year:2024,...gp('turbo-dismounting'),desc:'Destruição de carros para dois jogadores!',descLong:'Derby de Colisão 2P é o simulador de acidentes mais divertido para duplas. Cada jogador posiciona seu boneco e os carros se colidem. Quem pontua mais vence.',tags:['acidente','2 jogadores','destruição','física','diversão']},
  {id:'stickman-duel-2p',cat:'2jogadores',badge:'top',name:'Stickman Duel 2P',namePT:'Duelo Stickman 2P',emoji:'⚔️',rating:4.8,plays:1400000,year:2024,...gp('stickman-street-fighting'),desc:'Duelo épico de stickmen no mesmo teclado!',descLong:'Duelo Stickman 2P é o confronto mais épico para dois locais. Use metades do teclado para controlar cada lutador e prove quem é o melhor stickman guerreiro.',tags:['stickman','duelo','2 jogadores','luta','combate']},

];
